import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { FBXLoader } from "three/examples/jsm/loaders/FBXLoader.js";
import { IAsset } from "./iasset";
import { Char } from "./assettypes";
import { DeadtreeFab } from "./plant/deadtreefab";
import { MaleFab } from "./malefab";
import { FemaleFab } from "./femalefab";
import { MushroomFab } from "./plant/mushroomfab";
import { DeadTree2Fab, TreeFab } from "./plant/treefab";
import { PortalFab } from "./portalfab";
import { TestFab } from "./testfab";
import { ZombieFab } from "./monster/zombiefab";
import { BatFab } from "./item/batfab";
import { OldGunFab } from "./item/gunfab";
import { MinataurFab } from "./monster/minataurfab";
import { CrabFab } from "./monster/crabfab";
import { StoneFab } from "./stonefab";
import { HammerFab, WarteringCanFab } from "./plant/farmtoolsfab";
import { BedFab, ClosetFab, DeskFab } from "./furniture/funiturefab";
import { AppleTreeFab, CoconutTreeFab } from "./plant/plantfab";
import { BatPigFab } from "./monster/batpigfab";
import { BirdMonFab } from "./monster/birdmonfab";
import { BilbyFab } from "./pet/bilbyfab";
import { WereWolfFab } from "./monster/werewolffab";
import { BigGolemFab, GolemFab } from "./monster/golemfab";
import { SnakeFab } from "./monster/snakefab";
import { VikingFab } from "./monster/vikingfab";
import { BuilderFab } from "./monster/builderfab";
import { ToadMageFab } from "./monster/toadmagefab";
import { KittenMonkFab } from "./monster/kittenmonk";
import { SkeletonFab } from "./monster/skeleton";
import { Tomato0Fab, Tomato1Fab, Tomato2Fab } from "./plant/tomatofab";
import { Carrot0Fab, Carrot1Fab, Carrot2Fab } from "./plant/carrotfab";
import { Potato0Fab, Potato1Fab, Potato2Fab } from "./plant/potatofab";
import { BathFab, SinkFab, ToiletFab } from "./furniture/bathfab";
import { BookShelfFab, TableFab, TvFab } from "./furniture/livingfab";
import { KitTableFab, KitchenFab, OvenFab, RefrigeratorFab } from "./furniture/kitchenfab";
import { AppleFab, CoconutFab } from "./plant/fruitfab";
import { DogFab } from "./pet/dogfab";
import { PetSnakeFab } from "./pet/animalpackfab";
import { BeeFab } from "./pet/bee";
import { EmptyFab } from "./emptyfab";
import { HellBoyFab } from "./hellboy";
import { CuteGirlFab } from "./cutegirl";
import { OfficeGirlFab } from "./officegirl";
import { WizardFab } from "./wizardfab";
import { TwoBFab } from "./twobfab";
import { ArrowFab } from "./arrowfab";
import { GrassFab } from "./plant/grassfab";
import { FluffyTreeFab } from "./plant/fluffytree";
import { CatFab } from "./pet/catfab";
import { KayKitSkeletonAXeFab, KayKitSkeletonArrowBrokenFab, KayKitSkeletonArrowBrokenHalfFab, KayKitSkeletonArrowFab, KayKitSkeletonArrowHalfFab, KayKitSkeletonBladeFab, KayKitSkeletonCrossbowFab, KayKitSkeletonQuiverFab, KayKitSkeletonShieldLargeAFab, KayKitSkeletonShieldLargeBFab, KayKitSkeletonShieldSmallAFab, KayKitSkeletonShieldSmallBFab, KayKitSkeletonStaffFab } from "./kaykit/items/skeletonsitems";
import { KayKitSkeletonMageFab, KayKitSkeletonMinionFab, KayKitSkeletonRogueFab, KayKitSkeletonWarriorFab } from "./kaykit/skeletons/skeletons";
import { KayKitAdvBarbarianFab, KayKitAdvKnightFab, KayKitAdvMageFab, KayKitAdvRogueFab, KayKitAdvRogueHoodedFab } from "./kaykit/adventuerers/adventurers";
import { KayKitArrowBundleFab, KayKitArrowFab, KayKitAxe1HandedFab, KayKitAxe2HandedFab, KayKitCrossbow1HandedFab, KayKitCrossbow2HandedFab, KayKitDaggerFab, KayKitMugEmptyFab, KayKitMugFullFab, KayKitQuiverFab, KayKitShieldBadgeColorFab, KayKitShieldBadgeFab, KayKitShieldRoundBarbarianFab, KayKitShieldRoundColorFab, KayKitShieldRoundFab, KayKitShieldSpikesColorFab, KayKitShieldSpikesFab, KayKitShieldSquareColorFab, KayKitShieldSquareFab, KayKitSmokeBombFab, KayKitSpellbookClosedFab, KayKitSpellbookOpenFab, KayKitStaffFab, KayKitSword1HandedFab, KayKitSword2HandedColorFab, KayKitSword2HandedFab, KayKitWandFab } from "./kaykit/items/advitems";
import { OceanStarterAnemonieFab, OceanStarterChestFab, OceanStarterChestOldFab, OceanStarterCrashedShipFab, OceanStarterLongPlantFab, OceanStarterPirateShipFab, OceanStarterSmallBoatFab, OceanStarterSmallCoralFab, OceanStarterSubmarineFab } from "./oceanpack/oceanpack";
import { EasypackFrogFab, EasypackRatFab, EasypackSlimeFab, EasypackSnakeAngryFab, EasypackSnakeFab, EasypackSpiderFab, EasypackWaspFab } from "./monster/easypack";
import { OceanDolphinFab, OceanFish1Fab, OceanFish2Fab, OceanFish3Fab, OceanMantaRayFab, OceanSharkFab, OceanWhaleFab } from "./oceanpack/oceananimalfab";
import { UltimateCharFab, UltimateCharGunFab } from "./ultimatepack/charactersfab";
import { UltimateCubeBricksFab, UltimateCubeCrateFab, UltimateCubeDefaultFab, UltimateCubeDirtSingleFab, UltimateCubeExclamationFab, UltimateCubeGrassSingleFab, UltimateCubeQuestionFab } from "./ultimatepack/cubefab";
import { UltimateEnermyBeeFab, UltimateEnermyCrabFab, UltimateEnermyFab, UltimateEnermySkullFab } from "./ultimatepack/enermyfab";
import { UltimateLvAndMaArrowFab, UltimateLvAndMaArrowSideFab, UltimateLvAndMaArrowUpFab, UltimateLvAndMaBombFab, UltimateLvAndMaBouncerFab, UltimateLvAndMaBridgeModularCenterFab, UltimateLvAndMaBridgeModularFab, UltimateLvAndMaBridgeSmallFab, UltimateLvAndMaCannonBallFab, UltimateLvAndMaCannonFab, UltimateLvAndMaChestFab, UltimateLvAndMaDoorFab, UltimateLvAndMaFence1Fab, UltimateLvAndMaFenceCornerFab, UltimateLvAndMaFenceMiddleFab, UltimateLvAndMaGoalFlagFab, UltimateLvAndMaHazardCylinderFab, UltimateLvAndMaHazardSawFab, UltimateLvAndMaHazardSpikeTrapFab, UltimateLvAndMaLeverFab, UltimateLvAndMaNumber0Fab, UltimateLvAndMaNumber1Fab, UltimateLvAndMaNumber2Fab, UltimateLvAndMaNumber3Fab, UltimateLvAndMaNumber4Fab, UltimateLvAndMaNumber5Fab, UltimateLvAndMaNumber6Fab, UltimateLvAndMaNumber7Fab, UltimateLvAndMaNumber8Fab, UltimateLvAndMaNumber9Fab, UltimateLvAndMaPipe90Fab, UltimateLvAndMaPipeEndFab, UltimateLvAndMaPipeStraightFab, UltimateLvAndMaPipeTFab, UltimateLvAndMaPlantLargeFab, UltimateLvAndMaPlantSmallFab, UltimateLvAndMaSpikesFab, UltimateLvAndMaSpikyBallFab, UltimateLvAndMaStairsFab, UltimateLvAndMaStairsModularEndFab, UltimateLvAndMaStairsModularMiddleFab, UltimateLvAndMaStairsModularStartFab, UltimateLvAndMaStairsSmallFab, UltimateLvAndMaTowerFab } from "./ultimatepack/lvandmachinefab";
import { UltimateModPlatform2DCubeDirt1x1CenterFab, UltimateModPlatform2DCubeDirt1x1EndFab, UltimateModPlatform2DCubeGrass1x1CenterFab, UltimateModPlatform2DCubeGrass1x1EndFab, UltimateModPlatform3DCubeDirtCenterTallFab, UltimateModPlatform3DCubeDirtCornerTallFab, UltimateModPlatform3DCubeDirtSideTallFab, UltimateModPlatform3DCubeGrassBottomTallFab, UltimateModPlatform3DCubeGrassCornerBottomTallFab, UltimateModPlatform3DCubeGrassCornerCenterTallFab, UltimateModPlatform3DCubeGrassCornerTallFab, UltimateModPlatform3DCubeGrassSideBottomTallFab, UltimateModPlatform3DCubeGrassSideCenterTallFab, UltimateModPlatform3DCubeGrassSideTallFab, UltimateModPlatformSingleCubeDirtFab, UltimateModPlatformSingleCubeGrassFab, UltimateModPlatformSingleHeightDirtCenterFab, UltimateModPlatformSingleHeightDirtCornerFab, UltimateModPlatformSingleHeightDirtSideFab, UltimateModPlatformSingleHeightGrassCenterFab, UltimateModPlatformSingleHeightGrassCornerFab, UltimateModPlatformSingleHeightGrassSideFab } from "./ultimatepack/modplatformfab";
import { UltimateNatureBushFab, UltimateNatureBushFruitFab, UltimateNatureCloud1Fab, UltimateNatureCloud2Fab, UltimateNatureCloud3Fab, UltimateNatureFruitFab, UltimateNatureGrass1Fab, UltimateNatureGrass2Fab, UltimateNatureGrass3Fab, UltimateNatureRock1Fab, UltimateNatureRock2Fab, UltimateNatureRockPlatformTallFab, UltimateNatureRockPlatforms1Fab, UltimateNatureRockPlatforms2Fab, UltimateNatureRockPlatforms3Fab, UltimateNatureRockPlatformsLargeFab, UltimateNatureRockPlatformsMediumFab, UltimateNatureTreeFab, UltimateNatureTreeFruitFab } from "./ultimatepack/naturefab";
import { UltimatePAPCoinFab, UltimatePAPGemBlueFab, UltimatePAPGemGreenFab, UltimatePAPGemPinkFab, UltimatePAPHeartFab, UltimatePAPHeartHalfFab, UltimatePAPHeartOutlineFab, UltimatePAPKeyFab, UltimatePAPStarFab, UltimatePAPStarOutlineFab, UltimatePAPThunderFab } from "./ultimatepack/powerpickupfab";
import { FarmPetCowFab, FarmPetHorseFab, FarmPetLlamaFab, FarmPetPigFab, FarmPetPugFab, FarmPetSheepFab, FarmPetZebraFab } from "./pet/farmanimalfab";
import { FoxishFab } from "./monster/foxishfab";
import { PantherBlackWhiteFab, PantherBlueFab, PantherRedFab } from "./monster/pantherfab";
import { KenneyCriminalMaleFab, KenneyCyborgFemaleFab, KenneyHumanFemaleFab, KenneyHumanMaleFab, KenneySkaterFemaleFab, KenneySkaterMaleFab, KenneySurvivorFemaleFab, KenneySurvivorMaleFab, KenneyZombieAFab, KenneyZombieBFab, KenneyZombieFemaleAFab, KenneyZombieFemaleBFab } from "./kenney/charactersfab";
import { KayKitDungeonArrowFab, KayKitDungeonArtifactFab, KayKitDungeonAxedoubleCommonFab, KayKitDungeonAxedoubleRareFab, KayKitDungeonAxedoubleUncommonFab, KayKitDungeonAxeCommonFab, KayKitDungeonAxeRareFab, KayKitDungeonAxeUncommonFab, KayKitDungeonBannerFab, KayKitDungeonBarrelFab, KayKitDungeonBarreldarkFab, KayKitDungeonBenchFab, KayKitDungeonBookaFab, KayKitDungeonBookbFab, KayKitDungeonBookcFab, KayKitDungeonBookdFab, KayKitDungeonBookeFab, KayKitDungeonBookfFab, KayKitDungeonBookopenaFab, KayKitDungeonBookopenbFab, KayKitDungeonBookcaseFab, KayKitDungeonBookcasefilledFab, KayKitDungeonBookcasefilledBrokenFab, KayKitDungeonBookcasewideFab, KayKitDungeonBookcasewidefilledFab, KayKitDungeonBookcasewidefilledBrokenFab, KayKitDungeonBookcasewideBrokenFab, KayKitDungeonBookcaseBrokenFab, KayKitDungeonBricksFab, KayKitDungeonBucketFab, KayKitDungeonChairFab, KayKitDungeonChesttopCommonFab, KayKitDungeonChesttopCommonEmptyFab, KayKitDungeonChesttopRareFab, KayKitDungeonChesttopRareMimicFab, KayKitDungeonChesttopUncommonFab, KayKitDungeonChesttopUncommonMimicFab, KayKitDungeonChestCommonFab, KayKitDungeonChestCommonEmptyFab, KayKitDungeonChestRareFab, KayKitDungeonChestRareMimicFab, KayKitDungeonChestUncommonFab, KayKitDungeonChestUncommonMimicFab, KayKitDungeonCoinFab, KayKitDungeonCoinslargeFab, KayKitDungeonCoinsmediumFab, KayKitDungeonCoinssmallFab, KayKitDungeonCrateFab, KayKitDungeonCratedarkFab, KayKitDungeonCrateplatformLargeFab, KayKitDungeonCrateplatformMediumFab, KayKitDungeonCrateplatformSmallFab, KayKitDungeonCrossbowCommonFab, KayKitDungeonCrossbowRareFab, KayKitDungeonCrossbowUncommonFab, KayKitDungeonDaggerCommonFab, KayKitDungeonDaggerRareFab, KayKitDungeonDaggerUncommonFab, KayKitDungeonDoorFab, KayKitDungeonDoorGateFab, KayKitDungeonFloordecorationShatteredbricksFab, KayKitDungeonFloordecorationTileslargeFab, KayKitDungeonFloordecorationTilessmallFab, KayKitDungeonFloordecorationWoodFab, KayKitDungeonFloordecorationWoodleftFab, KayKitDungeonFloordecorationWoodrightFab, KayKitDungeonHammerCommonFab, KayKitDungeonHammerRareFab, KayKitDungeonHammerUncommonFab, KayKitDungeonLootsackaFab, KayKitDungeonLootsackbFab, KayKitDungeonMugFab, KayKitDungeonPillarFab, KayKitDungeonPillarBrokenFab, KayKitDungeonPlateFab, KayKitDungeonPlatefullFab, KayKitDungeonPlatehalfFab, KayKitDungeonPotaFab, KayKitDungeonPotaDecoratedFab, KayKitDungeonPotbFab, KayKitDungeonPotbDecoratedFab, KayKitDungeonPotcFab, KayKitDungeonPotcDecoratedFab, KayKitDungeonPotionlargeBlueFab, KayKitDungeonPotionlargeGreenFab, KayKitDungeonPotionlargeRedFab, KayKitDungeonPotionmediumBlueFab, KayKitDungeonPotionmediumGreenFab, KayKitDungeonPotionmediumRedFab, KayKitDungeonPotionsmallBlueFab, KayKitDungeonPotionsmallGreenFab, KayKitDungeonPotionsmallRedFab, KayKitDungeonPotsFab, KayKitDungeonQuiverEmptyFab, KayKitDungeonQuiverFullFab, KayKitDungeonQuiverHalfFullFab, KayKitDungeonScaffoldHighFab, KayKitDungeonScaffoldHighCornerbothFab, KayKitDungeonScaffoldHighCornerleftFab, KayKitDungeonScaffoldHighCornerrightFab, KayKitDungeonScaffoldHighRailingFab, KayKitDungeonScaffoldLowFab, KayKitDungeonScaffoldLowCornerbothFab, KayKitDungeonScaffoldLowCornerleftFab, KayKitDungeonScaffoldLowCornerrightFab, KayKitDungeonScaffoldLowRailingFab, KayKitDungeonScaffoldMediumFab, KayKitDungeonScaffoldMediumCornerbothFab, KayKitDungeonScaffoldMediumCornerleftFab, KayKitDungeonScaffoldMediumCornerrightFab, KayKitDungeonScaffoldMediumRailingFab, KayKitDungeonScaffoldSmallHighFab, KayKitDungeonScaffoldSmallHighCornerleftFab, KayKitDungeonScaffoldSmallHighCornerrightFab, KayKitDungeonScaffoldSmallHighLongFab, KayKitDungeonScaffoldSmallHighRailingFab, KayKitDungeonScaffoldSmallHighRailingLongFab, KayKitDungeonScaffoldSmallLowFab, KayKitDungeonScaffoldSmallLowCornerleftFab, KayKitDungeonScaffoldSmallLowCornerrightFab, KayKitDungeonScaffoldSmallLowLongFab, KayKitDungeonScaffoldSmallLowRailingFab, KayKitDungeonScaffoldSmallLowRailingLongFab, KayKitDungeonScaffoldSmallMediumFab, KayKitDungeonScaffoldSmallMediumCornerleftFab, KayKitDungeonScaffoldSmallMediumCornerrightFab, KayKitDungeonScaffoldSmallMediumLongFab, KayKitDungeonScaffoldSmallMediumRailingFab, KayKitDungeonScaffoldSmallMediumRailingLongFab, KayKitDungeonScaffoldStairsFab, KayKitDungeonShieldCommonFab, KayKitDungeonShieldRareFab, KayKitDungeonShieldUncommonFab, KayKitDungeonSpellbookFab, KayKitDungeonStaffCommonFab, KayKitDungeonStaffRareFab, KayKitDungeonStaffUncommonFab, KayKitDungeonStairsFab, KayKitDungeonStairsWideFab, KayKitDungeonStoolFab, KayKitDungeonSwordCommonFab, KayKitDungeonSwordRareFab, KayKitDungeonSwordUncommonFab, KayKitDungeonTablelargeFab, KayKitDungeonTablemediumFab, KayKitDungeonTablesmallFab, KayKitDungeonTilebrickaLargeFab, KayKitDungeonTilebrickaMediumFab, KayKitDungeonTilebrickaSmallFab, KayKitDungeonTilebrickbLargeFab, KayKitDungeonTilebrickbLargecrackedaFab, KayKitDungeonTilebrickbLargecrackedbFab, KayKitDungeonTilebrickbMediumFab, KayKitDungeonTilebrickbSmallFab, KayKitDungeonTilespikesFab, KayKitDungeonTilespikesLargeFab, KayKitDungeonTilespikesShallowFab, KayKitDungeonTorchFab, KayKitDungeonTorchwallFab, KayKitDungeonTrapdoorFab, KayKitDungeonWallFab, KayKitDungeonWallcornerFab, KayKitDungeonWalldecorationaFab, KayKitDungeonWalldecorationbFab, KayKitDungeonWallintersectionFab, KayKitDungeonWallsingleFab, KayKitDungeonWallsingleBrokenFab, KayKitDungeonWallsingleCornerFab, KayKitDungeonWallsingleDecorationaFab, KayKitDungeonWallsingleDecorationbFab, KayKitDungeonWallsingleDoorFab, KayKitDungeonWallsingleSplitFab, KayKitDungeonWallsingleWindowFab, KayKitDungeonWallsingleWindowgateFab, KayKitDungeonWallsplitFab, KayKitDungeonWallBrokenFab, KayKitDungeonWallDoorFab, KayKitDungeonWallEndFab, KayKitDungeonWallEndBrokenFab, KayKitDungeonWallGateFab, KayKitDungeonWallGatecornerFab, KayKitDungeonWallGatedoorFab, KayKitDungeonWallWindowFab, KayKitDungeonWallWindowgateFab, KayKitDungeonWeaponrackFab, } from "./kaykit/dungeon_pack/dungeonfab";
import { QuaterniusZombieCharactersGermanshepherdFab, QuaterniusZombieCharactersLisFab, QuaterniusZombieCharactersLisSingleweaponFab, QuaterniusZombieCharactersMattFab, QuaterniusZombieCharactersMattSingleweaponFab, QuaterniusZombieCharactersPugFab, QuaterniusZombieCharactersSamFab, QuaterniusZombieCharactersSamSingleweaponFab, QuaterniusZombieCharactersShaunFab, QuaterniusZombieCharactersShaunSingleweaponFab, QuaterniusZombieZombieArmFab, QuaterniusZombieZombieBasicFab, QuaterniusZombieZombieChubbyFab, QuaterniusZombieZombieRibcageFab,} from "./quaterniuspack/qzombiefab" 
import { QuaterniusNatureBushCommonFab, QuaterniusNatureBushCommonFlowersFab, QuaterniusNatureClover1Fab, QuaterniusNatureClover2Fab, QuaterniusNatureCommontree1Fab, QuaterniusNatureCommontree2Fab, QuaterniusNatureCommontree3Fab, QuaterniusNatureCommontree4Fab, QuaterniusNatureCommontree5Fab, QuaterniusNatureDeadtree1Fab, QuaterniusNatureDeadtree2Fab, QuaterniusNatureDeadtree3Fab, QuaterniusNatureDeadtree4Fab, QuaterniusNatureDeadtree5Fab, QuaterniusNatureFern1Fab, QuaterniusNatureFlower3GroupFab, QuaterniusNatureFlower3SingleFab, QuaterniusNatureFlower4GroupFab, QuaterniusNatureFlower4SingleFab, QuaterniusNatureGrassCommonShortFab, QuaterniusNatureGrassCommonTallFab, QuaterniusNatureGrassWispyShortFab, QuaterniusNatureGrassWispyTallFab, QuaterniusNatureMushroomCommonFab, QuaterniusNatureMushroomLaetiporusFab, QuaterniusNaturePebbleRound1Fab, QuaterniusNaturePebbleRound2Fab, QuaterniusNaturePebbleRound3Fab, QuaterniusNaturePebbleRound4Fab, QuaterniusNaturePebbleRound5Fab, QuaterniusNaturePebbleSquare1Fab, QuaterniusNaturePebbleSquare2Fab, QuaterniusNaturePebbleSquare3Fab, QuaterniusNaturePebbleSquare4Fab, QuaterniusNaturePebbleSquare5Fab, QuaterniusNaturePebbleSquare6Fab, QuaterniusNaturePetal1Fab, QuaterniusNaturePetal2Fab, QuaterniusNaturePetal3Fab, QuaterniusNaturePetal4Fab, QuaterniusNaturePetal5Fab, QuaterniusNaturePine1Fab, QuaterniusNaturePine2Fab, QuaterniusNaturePine3Fab, QuaterniusNaturePine4Fab, QuaterniusNaturePine5Fab, QuaterniusNaturePlant1Fab, QuaterniusNaturePlant1BigFab, QuaterniusNaturePlant7Fab, QuaterniusNaturePlant7BigFab, QuaterniusNatureRockpathRoundSmall1Fab, QuaterniusNatureRockpathRoundSmall2Fab, QuaterniusNatureRockpathRoundSmall3Fab, QuaterniusNatureRockpathRoundThinFab, QuaterniusNatureRockpathRoundWideFab, QuaterniusNatureRockpathSquareSmall1Fab, QuaterniusNatureRockpathSquareSmall2Fab, QuaterniusNatureRockpathSquareSmall3Fab, QuaterniusNatureRockpathSquareThinFab, QuaterniusNatureRockpathSquareWideFab, QuaterniusNatureRockMedium1Fab, QuaterniusNatureRockMedium2Fab, QuaterniusNatureRockMedium3Fab, QuaterniusNatureTwistedtree1Fab, QuaterniusNatureTwistedtree2Fab, QuaterniusNatureTwistedtree3Fab, QuaterniusNatureTwistedtree4Fab, QuaterniusNatureTwistedtree5Fab, } from "./quaterniuspack/qnaturefab" 
import { QuaterniusCard0CardBackFab, QuaterniusCard0CardContainerFab, QuaterniusCard0CardFrontFab, QuaterniusCard0CardMaskFab, QuaterniusCard10BeehiveFab, QuaterniusCard11PolinizationFab, QuaterniusCard12MimicFab, QuaterniusCard13SeamonsterFab, QuaterniusCard14CoinFab, QuaterniusCard15CultFab, QuaterniusCard16BelltowersFab, QuaterniusCard17RebirthFab, QuaterniusCard18WaterdragonFab, QuaterniusCard19OceantreasureFab, QuaterniusCard1FireballFab, QuaterniusCard20ElementFireFab, QuaterniusCard21ElementLightningFab, QuaterniusCard22ElementAirFab, QuaterniusCard23ElementWaterFab, QuaterniusCard24ElementDarkFab, QuaterniusCard25ElementEarthFab, QuaterniusCard26BloodringFab, QuaterniusCard27BookFab, QuaterniusCard28RolldiceFab, QuaterniusCard29BlockFab, QuaterniusCard2TrenchcoatmushroomsFab, QuaterniusCard30WizardFab, QuaterniusCard3MonkFab, QuaterniusCard4MarketFab, QuaterniusCard5StealFab, QuaterniusCard6KingFab, QuaterniusCard7StinktrapFab, QuaterniusCard8LightningwizardFab, QuaterniusCard9HypnosisFab,  } from "./quaterniuspack/qcardfab" 
import { QuaterniusAniCharBasecharacterFab, QuaterniusAniCharBluesoldierFemaleFab, QuaterniusAniCharBluesoldierMaleFab, QuaterniusAniCharCasual2FemaleFab, QuaterniusAniCharCasual2MaleFab, QuaterniusAniCharCasual3FemaleFab, QuaterniusAniCharCasual3MaleFab, QuaterniusAniCharCasualBaldFab, QuaterniusAniCharCasualFemaleFab, QuaterniusAniCharCasualMaleFab, QuaterniusAniCharChefFemaleFab, QuaterniusAniCharChefHatFab, QuaterniusAniCharChefMaleFab, QuaterniusAniCharCowFab, QuaterniusAniCharCowboyFemaleFab, QuaterniusAniCharCowboyHairFab, QuaterniusAniCharCowboyMaleFab, QuaterniusAniCharDoctorFemaleOldFab, QuaterniusAniCharDoctorFemaleYoungFab, QuaterniusAniCharDoctorMaleOldFab, QuaterniusAniCharDoctorMaleYoungFab, QuaterniusAniCharElfFab, QuaterniusAniCharGoblinFemaleFab, QuaterniusAniCharGoblinMaleFab, QuaterniusAniCharKimonoFemaleFab, QuaterniusAniCharKimonoMaleFab, QuaterniusAniCharKnightGoldenFemaleFab, QuaterniusAniCharKnightGoldenMaleFab, QuaterniusAniCharKnightMaleFab, QuaterniusAniCharNinjaFemaleFab, QuaterniusAniCharNinjaMaleFab, QuaterniusAniCharNinjaMaleHairFab, QuaterniusAniCharNinjaSandFab, QuaterniusAniCharNinjaSandFemaleFab, QuaterniusAniCharOldclassyFemaleFab, QuaterniusAniCharOldclassyMaleFab, QuaterniusAniCharPirateFemaleFab, QuaterniusAniCharPirateMaleFab, QuaterniusAniCharPugFab, QuaterniusAniCharSoldierFemaleFab, QuaterniusAniCharSoldierMaleFab, QuaterniusAniCharSuitFemaleFab, QuaterniusAniCharSuitMaleFab, QuaterniusAniCharVikinghelmetFab, QuaterniusAniCharVikingFemaleFab, QuaterniusAniCharVikingMaleFab, QuaterniusAniCharWitchFab, QuaterniusAniCharWizardFab, QuaterniusAniCharWorkerFemaleFab, QuaterniusAniCharWorkerMaleFab, QuaterniusAniCharZombieFemaleFab, QuaterniusAniCharZombieMaleFab,} from "./quaterniuspack/qanimatedcharfab"
import { M4A1Fab, PistolFab } from "./item/gunfbxfab";

// Fab 클래스 타입
type FabConstructor = new (loader: Loader, ...args: any[]) => IAsset;

export class Loader {
    private fbxLoader = new FBXLoader();
    private loadingManager = new THREE.LoadingManager();
    private loader = new GLTFLoader(this.loadingManager);

    fabClasses = new Map<Char, FabConstructor>();
    private fabInstances = new Map<Char, IAsset>();

    constructor(public rootPath: string = "https://hons.ghostwebservice.com/") {
        THREE.Cache.enabled = true;

        this.registerFabs();
    }

    private registerFabs() {
        // 모든 Fab 클래스 등록 (생략 없이)
        this.fabClasses.set(Char.CharHumanMale, MaleFab);
        this.fabClasses.set(Char.CharHumanFemale, FemaleFab);
        this.fabClasses.set(Char.CharMonHellboy, HellBoyFab);
        this.fabClasses.set(Char.CharHumanCuteGirl, CuteGirlFab);
        this.fabClasses.set(Char.CharHumanOfficeGirl, OfficeGirlFab);
        this.fabClasses.set(Char.CharHumanWizard, WizardFab);
        this.fabClasses.set(Char.CharHumanTwoB, TwoBFab);
        this.fabClasses.set(Char.Arrow, ArrowFab);

        this.fabClasses.set(Char.Mushroom1, MushroomFab);
        this.fabClasses.set(Char.Mushroom2, MushroomFab);
        this.fabClasses.set(Char.Tree, TreeFab);
        this.fabClasses.set(Char.DeadTree, DeadtreeFab);
        this.fabClasses.set(Char.Portal, PortalFab);
        this.fabClasses.set(Char.Test, TestFab);

        // Kenney
        this.fabClasses.set(Char.CharHumanKenneyCriminalMale, KenneyCriminalMaleFab);
        this.fabClasses.set(Char.CharHumanKenneyCyborgFemale, KenneyCyborgFemaleFab);
        this.fabClasses.set(Char.CharHumanKenneyHumanFemale, KenneyHumanFemaleFab);
        this.fabClasses.set(Char.CharHumanKenneyHumanMale, KenneyHumanMaleFab);
        this.fabClasses.set(Char.CharHumanKenneySkaterFemale, KenneySkaterFemaleFab);
        this.fabClasses.set(Char.CharHumanKenneySkaterMale, KenneySkaterMaleFab);
        this.fabClasses.set(Char.CharHumanKenneySurvivorFemale, KenneySurvivorFemaleFab);
        this.fabClasses.set(Char.CharHumanKenneySurvivorMale, KenneySurvivorMaleFab);
        this.fabClasses.set(Char.CharMonKenneyZombieA, KenneyZombieAFab);
        this.fabClasses.set(Char.CharMonKenneyZombieB, KenneyZombieBFab);
        this.fabClasses.set(Char.CharMonKenneyZombieFemaleA, KenneyZombieFemaleAFab);
        this.fabClasses.set(Char.CharMonKenneyZombieFemaleB, KenneyZombieFemaleBFab);

        // Monster
        this.fabClasses.set(Char.CharMonZombie, ZombieFab);
        this.fabClasses.set(Char.CharMonMinataur, MinataurFab);
        this.fabClasses.set(Char.CharMonCrab, CrabFab);
        this.fabClasses.set(Char.CharMonBatPig, BatPigFab);
        this.fabClasses.set(Char.CharMonBird, BirdMonFab);
        this.fabClasses.set(Char.CharMonWereWolf, WereWolfFab);
        this.fabClasses.set(Char.CharMonGolem, GolemFab);
        this.fabClasses.set(Char.CharMonBigGolem, BigGolemFab);
        this.fabClasses.set(Char.CharMonSnake, SnakeFab);
        this.fabClasses.set(Char.CharHumanViking, VikingFab);
        this.fabClasses.set(Char.CharHumanBuilder, BuilderFab);
        this.fabClasses.set(Char.CharMonToadMage, ToadMageFab);
        this.fabClasses.set(Char.CharMonKittenMonk, KittenMonkFab);
        this.fabClasses.set(Char.CharMonSkeleton, SkeletonFab);
        this.fabClasses.set(Char.CharAniFoxish, FoxishFab);
        this.fabClasses.set(Char.CharMonPantherBlackWhite, PantherBlackWhiteFab);
        this.fabClasses.set(Char.CharMonPantherBlue, PantherBlueFab);
        this.fabClasses.set(Char.CharAniPantherRed, PantherRedFab);

        // KayKit
        this.fabClasses.set(Char.CharMonKayKitSkeletonMage, KayKitSkeletonMageFab);
        this.fabClasses.set(Char.CharMonKayKitSkeletonWarrior, KayKitSkeletonWarriorFab);
        this.fabClasses.set(Char.CharMonKayKitSkeletonRogue, KayKitSkeletonRogueFab);
        this.fabClasses.set(Char.CharMonKayKitSkeletonMinion, KayKitSkeletonMinionFab);

        this.fabClasses.set(Char.KayKitSkeletonArrow, KayKitSkeletonArrowFab);
        this.fabClasses.set(Char.KayKitSkeletonArrowBroken, KayKitSkeletonArrowBrokenFab);
        this.fabClasses.set(Char.KayKitSkeletonArrowBrokenHalf, KayKitSkeletonArrowBrokenHalfFab);
        this.fabClasses.set(Char.KayKitSkeletonArrowHalf, KayKitSkeletonArrowHalfFab);
        this.fabClasses.set(Char.KayKitSkeletonAxe, KayKitSkeletonAXeFab);
        this.fabClasses.set(Char.KayKitSkeletonBlade, KayKitSkeletonBladeFab);
        this.fabClasses.set(Char.KayKitSkeletonCrossbow, KayKitSkeletonCrossbowFab);
        this.fabClasses.set(Char.KayKitSkeletonQuiver, KayKitSkeletonQuiverFab);
        this.fabClasses.set(Char.KayKitSkeletonShieldLarge_A, KayKitSkeletonShieldLargeAFab);
        this.fabClasses.set(Char.KayKitSkeletonShieldLarge_B, KayKitSkeletonShieldLargeBFab);
        this.fabClasses.set(Char.KayKitSkeletonShieldSmall_A, KayKitSkeletonShieldSmallAFab);
        this.fabClasses.set(Char.KayKitSkeletonShieldSmall_B, KayKitSkeletonShieldSmallBFab);
        this.fabClasses.set(Char.KayKitSkeletonStaff, KayKitSkeletonStaffFab);

        this.fabClasses.set(Char.CharHumanKayKitAdvBarbarian, KayKitAdvBarbarianFab);
        this.fabClasses.set(Char.CharHumanKayKitAdvKnight, KayKitAdvKnightFab);
        this.fabClasses.set(Char.CharHumanKayKitAdvMage, KayKitAdvMageFab);
        this.fabClasses.set(Char.CharHumanKayKitAdvRogue, KayKitAdvRogueFab);
        this.fabClasses.set(Char.CharHumanKayKitAdvRogueHooded, KayKitAdvRogueHoodedFab);

        this.fabClasses.set(Char.KayKitAdvArrow, KayKitArrowFab);
        this.fabClasses.set(Char.KayKitAdvArrowBundle, KayKitArrowBundleFab);
        this.fabClasses.set(Char.KayKitAdvAxe1Handed, KayKitAxe1HandedFab);
        this.fabClasses.set(Char.KayKitAdvAxe2Handed, KayKitAxe2HandedFab);
        this.fabClasses.set(Char.KayKitAdvCrossbow1Handed, KayKitCrossbow1HandedFab);
        this.fabClasses.set(Char.KayKitAdvCrossbow2Handed, KayKitCrossbow2HandedFab);
        this.fabClasses.set(Char.KayKitAdvDagger, KayKitDaggerFab);
        this.fabClasses.set(Char.KayKitAdvMugEmpty, KayKitMugEmptyFab);
        this.fabClasses.set(Char.KayKitAdvMugFull, KayKitMugFullFab);
        this.fabClasses.set(Char.KayKitAdvQuiver, KayKitQuiverFab);
        this.fabClasses.set(Char.KayKitAdvShieldBadge, KayKitShieldBadgeFab);
        this.fabClasses.set(Char.KayKitAdvShieldBadgeColor, KayKitShieldBadgeColorFab);
        this.fabClasses.set(Char.KayKitAdvShieldRound, KayKitShieldRoundFab);
        this.fabClasses.set(Char.KayKitAdvShieldRoundBarbarian, KayKitShieldRoundBarbarianFab);
        this.fabClasses.set(Char.KayKitAdvShieldRoundColor, KayKitShieldRoundColorFab);
        this.fabClasses.set(Char.KayKitAdvShieldSpikes, KayKitShieldSpikesFab);
        this.fabClasses.set(Char.KayKitAdvShieldSpikesColor, KayKitShieldSpikesColorFab);
        this.fabClasses.set(Char.KayKitAdvShieldSquare, KayKitShieldSquareFab);
        this.fabClasses.set(Char.KayKitAdvShieldSquareColor, KayKitShieldSquareColorFab);
        this.fabClasses.set(Char.KayKitAdvSmokeBomb, KayKitSmokeBombFab);
        this.fabClasses.set(Char.KayKitAdvSpellbookClosed, KayKitSpellbookClosedFab);
        this.fabClasses.set(Char.KayKitAdvSpellbookOpen, KayKitSpellbookOpenFab);
        this.fabClasses.set(Char.KayKitAdvStaff, KayKitStaffFab);
        this.fabClasses.set(Char.KayKitAdvSword1Handed, KayKitSword1HandedFab);
        this.fabClasses.set(Char.KayKitAdvSword2Handed, KayKitSword2HandedFab);
        this.fabClasses.set(Char.KayKitAdvSword2HandedColor, KayKitSword2HandedColorFab);
        this.fabClasses.set(Char.KayKitAdvWand, KayKitWandFab);

        this.fabClasses.set(Char.OceanStarterSubMarine, OceanStarterSubmarineFab);
        this.fabClasses.set(Char.OceanStarterSmallCoral, OceanStarterSmallCoralFab);
        this.fabClasses.set(Char.OceanStarterSmallBoat, OceanStarterSmallBoatFab);
        this.fabClasses.set(Char.OceanStarterPirateShip, OceanStarterPirateShipFab);
        this.fabClasses.set(Char.OceanStarterLongPlant, OceanStarterLongPlantFab);
        this.fabClasses.set(Char.OceanStarterCrashedShip, OceanStarterCrashedShipFab);
        this.fabClasses.set(Char.OceanStarterChestOld, OceanStarterChestOldFab);
        this.fabClasses.set(Char.OceanStarterChest, OceanStarterChestFab);
        this.fabClasses.set(Char.OceanStarterAnemonie, OceanStarterAnemonieFab);

        this.fabClasses.set(Char.CharAniOceanDolphin, OceanDolphinFab);
        this.fabClasses.set(Char.CharAniOceanFish1, OceanFish1Fab);
        this.fabClasses.set(Char.CharAniOceanFish2, OceanFish2Fab);
        this.fabClasses.set(Char.CharAniOceanFish3, OceanFish3Fab);
        this.fabClasses.set(Char.CharAniOceanMantaRay, OceanMantaRayFab);
        this.fabClasses.set(Char.CharAniOceanShark, OceanSharkFab);
        this.fabClasses.set(Char.CharAniOceanWhale, OceanWhaleFab);

        this.fabClasses.set(Char.CharAniEasypackFrog, EasypackFrogFab);
        this.fabClasses.set(Char.CharAniEasypackRat, EasypackRatFab);
        this.fabClasses.set(Char.CharAniEasypackSnake, EasypackSnakeFab);
        this.fabClasses.set(Char.CharAniEasypackSnakeAngry, EasypackSnakeAngryFab);
        this.fabClasses.set(Char.CharAniEasypackSpider, EasypackSpiderFab);
        this.fabClasses.set(Char.CharAniEasypackWasp, EasypackWaspFab);
        this.fabClasses.set(Char.CharMonEasypackSlime, EasypackSlimeFab);


        this.fabClasses.set(Char.CharHumanUltimate, UltimateCharFab);
        this.fabClasses.set(Char.CharHumanUltimateGun, UltimateCharGunFab);
        this.fabClasses.set(Char.UltimateCubeBricks, UltimateCubeBricksFab);
        this.fabClasses.set(Char.UltimateCubeCrate, UltimateCubeCrateFab);
        this.fabClasses.set(Char.UltimateCubeDefault, UltimateCubeDefaultFab);
        this.fabClasses.set(Char.UltimateCubeDirtSingle, UltimateCubeDirtSingleFab);
        this.fabClasses.set(Char.UltimateCubeExclamation, UltimateCubeExclamationFab);
        this.fabClasses.set(Char.UltimateCubeGrassSingle, UltimateCubeGrassSingleFab);
        this.fabClasses.set(Char.UltimateCubeQuestion, UltimateCubeQuestionFab);
        this.fabClasses.set(Char.CharMonUltimateEnermyBee, UltimateEnermyBeeFab);
        this.fabClasses.set(Char.CharMonUltimateEnermyCrab, UltimateEnermyCrabFab);
        this.fabClasses.set(Char.CharMonUltimateEnermy, UltimateEnermyFab);
        this.fabClasses.set(Char.CharMonUltimateEnermySkull, UltimateEnermySkullFab);
        this.fabClasses.set(Char.UltimateLvAndMaArrow, UltimateLvAndMaArrowFab);
        this.fabClasses.set(Char.UltimateLvAndMaArrowSide, UltimateLvAndMaArrowSideFab);
        this.fabClasses.set(Char.UltimateLvAndMaArrowUp, UltimateLvAndMaArrowUpFab);
        this.fabClasses.set(Char.UltimateLvAndMaBomb, UltimateLvAndMaBombFab);
        this.fabClasses.set(Char.UltimateLvAndMaBouncer, UltimateLvAndMaBouncerFab);
        this.fabClasses.set(Char.UltimateLvAndMaBridgeModular, UltimateLvAndMaBridgeModularFab);
        this.fabClasses.set(Char.UltimateLvAndMaBridgeModularCenter, UltimateLvAndMaBridgeModularCenterFab);
        this.fabClasses.set(Char.UltimateLvAndMaBridgeSmall, UltimateLvAndMaBridgeSmallFab);
        this.fabClasses.set(Char.UltimateLvAndMaCannon, UltimateLvAndMaCannonFab);
        this.fabClasses.set(Char.UltimateLvAndMaCannonBall, UltimateLvAndMaCannonBallFab);
        this.fabClasses.set(Char.UltimateLvAndMaChest, UltimateLvAndMaChestFab);
        this.fabClasses.set(Char.UltimateLvAndMaDoor, UltimateLvAndMaDoorFab);
        this.fabClasses.set(Char.UltimateLvAndMaFence1, UltimateLvAndMaFence1Fab);
        this.fabClasses.set(Char.UltimateLvAndMaFenceCorner, UltimateLvAndMaFenceCornerFab);
        this.fabClasses.set(Char.UltimateLvAndMaFenceMiddle, UltimateLvAndMaFenceMiddleFab);
        this.fabClasses.set(Char.UltimateLvAndMaGoalFlag, UltimateLvAndMaGoalFlagFab);
        this.fabClasses.set(Char.UltimateLvAndMaHazardCylinder, UltimateLvAndMaHazardCylinderFab);
        this.fabClasses.set(Char.UltimateLvAndMaHazardSaw, UltimateLvAndMaHazardSawFab);
        this.fabClasses.set(Char.UltimateLvAndMaHazardSpikeTrap, UltimateLvAndMaHazardSpikeTrapFab);
        this.fabClasses.set(Char.UltimateLvAndMaLever, UltimateLvAndMaLeverFab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers0, UltimateLvAndMaNumber0Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers1, UltimateLvAndMaNumber1Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers2, UltimateLvAndMaNumber2Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers3, UltimateLvAndMaNumber3Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers4, UltimateLvAndMaNumber4Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers5, UltimateLvAndMaNumber5Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers6, UltimateLvAndMaNumber6Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers7, UltimateLvAndMaNumber7Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers8, UltimateLvAndMaNumber8Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers9, UltimateLvAndMaNumber9Fab);
        this.fabClasses.set(Char.UltimateLvAndMaPipe90, UltimateLvAndMaPipe90Fab);
        this.fabClasses.set(Char.UltimateLvAndMaPipeEnd, UltimateLvAndMaPipeEndFab);
        this.fabClasses.set(Char.UltimateLvAndMaPipeStraight, UltimateLvAndMaPipeStraightFab);
        this.fabClasses.set(Char.UltimateLvAndMaPipeT, UltimateLvAndMaPipeTFab);
        this.fabClasses.set(Char.UltimateLvAndMaPlantLarge, UltimateLvAndMaPlantLargeFab);
        this.fabClasses.set(Char.UltimateLvAndMaPlantSmall, UltimateLvAndMaPlantSmallFab);
        this.fabClasses.set(Char.UltimateLvAndMaSpikes, UltimateLvAndMaSpikesFab);
        this.fabClasses.set(Char.UltimateLvAndMaSpikyBall, UltimateLvAndMaSpikyBallFab);
        this.fabClasses.set(Char.UltimateLvAndMaStairs, UltimateLvAndMaStairsFab);
        this.fabClasses.set(Char.UltimateLvAndMaStairsModularEnd, UltimateLvAndMaStairsModularEndFab);
        this.fabClasses.set(Char.UltimateLvAndMaStairsModularMiddle, UltimateLvAndMaStairsModularMiddleFab);
        this.fabClasses.set(Char.UltimateLvAndMaStairsModularStart, UltimateLvAndMaStairsModularStartFab);
        this.fabClasses.set(Char.UltimateLvAndMaStairsSmall, UltimateLvAndMaStairsSmallFab);
        this.fabClasses.set(Char.UltimateLvAndMaTower, UltimateLvAndMaTowerFab);
        this.fabClasses.set(Char.UltimateModPlatform2DCubeDirt1x1Center, UltimateModPlatform2DCubeDirt1x1CenterFab);
        this.fabClasses.set(Char.UltimateModPlatform2DCubeDirt1x1End, UltimateModPlatform2DCubeDirt1x1EndFab);
        this.fabClasses.set(Char.UltimateModPlatform2DCubeGrass1x1Center, UltimateModPlatform2DCubeGrass1x1CenterFab);
        this.fabClasses.set(Char.UltimateModPlatform2DCubeGrass1x1End, UltimateModPlatform2DCubeGrass1x1EndFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeDirtCenterTall, UltimateModPlatform3DCubeDirtCenterTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeDirtCornerTall, UltimateModPlatform3DCubeDirtCornerTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeDirtSideTall, UltimateModPlatform3DCubeDirtSideTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassBottomTall, UltimateModPlatform3DCubeGrassBottomTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassCornerBottomTall, UltimateModPlatform3DCubeGrassCornerBottomTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassCornerCenterTall, UltimateModPlatform3DCubeGrassCornerCenterTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassCornerTall, UltimateModPlatform3DCubeGrassCornerTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassSideBottomTall, UltimateModPlatform3DCubeGrassSideBottomTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassSideCenterTall, UltimateModPlatform3DCubeGrassSideCenterTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassSideTall, UltimateModPlatform3DCubeGrassSideTallFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleCubeDirt, UltimateModPlatformSingleCubeDirtFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleCubeGrass, UltimateModPlatformSingleCubeGrassFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightDirtCenter, UltimateModPlatformSingleHeightDirtCenterFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightDirtCorner, UltimateModPlatformSingleHeightDirtCornerFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightDirtSide, UltimateModPlatformSingleHeightDirtSideFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightGrassCenter, UltimateModPlatformSingleHeightGrassCenterFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightGrassCorner, UltimateModPlatformSingleHeightGrassCornerFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightGrassSide, UltimateModPlatformSingleHeightGrassSideFab);
        this.fabClasses.set(Char.UltimateNatureBush, UltimateNatureBushFab);
        this.fabClasses.set(Char.UltimateNatureBushFruit, UltimateNatureBushFruitFab);
        this.fabClasses.set(Char.UltimateNatureCloud1, UltimateNatureCloud1Fab);
        this.fabClasses.set(Char.UltimateNatureCloud2, UltimateNatureCloud2Fab);
        this.fabClasses.set(Char.UltimateNatureCloud3, UltimateNatureCloud3Fab);
        this.fabClasses.set(Char.UltimateNatureFruit, UltimateNatureFruitFab);
        this.fabClasses.set(Char.UltimateNatureGrass1, UltimateNatureGrass1Fab);
        this.fabClasses.set(Char.UltimateNatureGrass2, UltimateNatureGrass2Fab);
        this.fabClasses.set(Char.UltimateNatureGrass3, UltimateNatureGrass3Fab);
        this.fabClasses.set(Char.UltimateNatureRock1, UltimateNatureRock1Fab);
        this.fabClasses.set(Char.UltimateNatureRock2, UltimateNatureRock2Fab);
        this.fabClasses.set(Char.UltimateNatureRockPlatformTall, UltimateNatureRockPlatformTallFab);
        this.fabClasses.set(Char.UltimateNatureRockPlatforms1, UltimateNatureRockPlatforms1Fab);
        this.fabClasses.set(Char.UltimateNatureRockPlatforms2, UltimateNatureRockPlatforms2Fab);
        this.fabClasses.set(Char.UltimateNatureRockPlatforms3, UltimateNatureRockPlatforms3Fab);
        this.fabClasses.set(Char.UltimateNatureRockPlatformsLarge, UltimateNatureRockPlatformsLargeFab);
        this.fabClasses.set(Char.UltimateNatureRockPlatformsMedium, UltimateNatureRockPlatformsMediumFab);
        this.fabClasses.set(Char.UltimateNatureTree, UltimateNatureTreeFab);
        this.fabClasses.set(Char.UltimateNatureTreeFruit, UltimateNatureTreeFruitFab);
        this.fabClasses.set(Char.UltimatePAPCoin, UltimatePAPCoinFab);
        this.fabClasses.set(Char.UltimatePAPGemBlue, UltimatePAPGemBlueFab);
        this.fabClasses.set(Char.UltimatePAPGemGreen, UltimatePAPGemGreenFab);
        this.fabClasses.set(Char.UltimatePAPGemPink, UltimatePAPGemPinkFab);
        this.fabClasses.set(Char.UltimatePAPHeart, UltimatePAPHeartFab);
        this.fabClasses.set(Char.UltimatePAPHeartHalf, UltimatePAPHeartHalfFab);
        this.fabClasses.set(Char.UltimatePAPHeartOutline, UltimatePAPHeartOutlineFab);
        this.fabClasses.set(Char.UltimatePAPKey, UltimatePAPKeyFab);
        this.fabClasses.set(Char.UltimatePAPStar, UltimatePAPStarFab);
        this.fabClasses.set(Char.UltimatePAPStarOutline, UltimatePAPStarOutlineFab);
        this.fabClasses.set(Char.UltimatePAPThunder, UltimatePAPThunderFab);

        // Pet
        this.fabClasses.set(Char.CharAniBilby, BilbyFab);
        this.fabClasses.set(Char.CharAniDog, DogFab);
        this.fabClasses.set(Char.CharAniCat, CatFab);
        this.fabClasses.set(Char.CharAniBee, BeeFab);
        this.fabClasses.set(Char.CharAniPetSnake, PetSnakeFab);

        // Farm Pet
        this.fabClasses.set(Char.CharAniFarmPetCow, FarmPetCowFab);
        this.fabClasses.set(Char.CharAniFarmPetHorse, FarmPetHorseFab);
        this.fabClasses.set(Char.CharAniFarmPetLlama, FarmPetLlamaFab);
        this.fabClasses.set(Char.CharAniFarmPetPig, FarmPetPigFab);
        this.fabClasses.set(Char.CharAniFarmPetPug, FarmPetPugFab);
        this.fabClasses.set(Char.CharAniFarmPetSheep, FarmPetSheepFab);
        this.fabClasses.set(Char.CharAniFarmPetZebra, FarmPetZebraFab);

        // Stup
        this.fabClasses.set(Char.ItemsBat, BatFab);
        this.fabClasses.set(Char.ItemsGun, OldGunFab);
        this.fabClasses.set(Char.ItemsPistol, PistolFab);
        this.fabClasses.set(Char.ItemsM4A1, M4A1Fab);
        this.fabClasses.set(Char.Stone, StoneFab);
        this.fabClasses.set(Char.Bed, BedFab);
        this.fabClasses.set(Char.Bath, BathFab);
        this.fabClasses.set(Char.Bookshelf, BookShelfFab);
        this.fabClasses.set(Char.Closet, ClosetFab);
        this.fabClasses.set(Char.Desk, DeskFab);
        this.fabClasses.set(Char.Kitchen, KitchenFab);
        this.fabClasses.set(Char.KitTable, KitTableFab);
        this.fabClasses.set(Char.Oven, OvenFab);
        this.fabClasses.set(Char.Refrigerator, RefrigeratorFab);
        this.fabClasses.set(Char.Sink, SinkFab);
        this.fabClasses.set(Char.Table, TableFab);
        this.fabClasses.set(Char.Toilet, ToiletFab);
        this.fabClasses.set(Char.TV, TvFab);

        this.fabClasses.set(Char.FluffyTree, FluffyTreeFab);
        this.fabClasses.set(Char.AppleTree, AppleTreeFab);
        this.fabClasses.set(Char.Apple, AppleFab);
        this.fabClasses.set(Char.CoconutTree, CoconutTreeFab);
        this.fabClasses.set(Char.Coconut, CoconutFab);
        this.fabClasses.set(Char.DeadTree2, DeadTree2Fab);
        this.fabClasses.set(Char.Tomato0, Tomato0Fab);
        this.fabClasses.set(Char.Tomato1, Tomato1Fab);
        this.fabClasses.set(Char.Tomato2, Tomato2Fab);
        this.fabClasses.set(Char.Potato0, Potato0Fab);
        this.fabClasses.set(Char.Potato1, Potato1Fab);
        this.fabClasses.set(Char.Potato2, Potato2Fab);
        this.fabClasses.set(Char.Carrot0, Carrot0Fab);
        this.fabClasses.set(Char.Carrot1, Carrot1Fab);
        this.fabClasses.set(Char.Carrot2, Carrot2Fab);

        this.fabClasses.set(Char.Grass, GrassFab);

        this.fabClasses.set(Char.ItemsWateringCan, WarteringCanFab);
        this.fabClasses.set(Char.ItemsHammer, HammerFab);

        this.fabClasses.set(Char.Empty, EmptyFab);


        // 추가 모델은 여기서 계속 등록
        this.fabClasses.set(Char.KayKitDungeonArrow, KayKitDungeonArrowFab);
        this.fabClasses.set(Char.KayKitDungeonArtifact, KayKitDungeonArtifactFab);
        this.fabClasses.set(Char.KayKitDungeonAxedoubleCommon, KayKitDungeonAxedoubleCommonFab);
        this.fabClasses.set(Char.KayKitDungeonAxedoubleRare, KayKitDungeonAxedoubleRareFab);
        this.fabClasses.set(Char.KayKitDungeonAxedoubleUncommon, KayKitDungeonAxedoubleUncommonFab);
        this.fabClasses.set(Char.KayKitDungeonAxeCommon, KayKitDungeonAxeCommonFab);
        this.fabClasses.set(Char.KayKitDungeonAxeRare, KayKitDungeonAxeRareFab);
        this.fabClasses.set(Char.KayKitDungeonAxeUncommon, KayKitDungeonAxeUncommonFab);
        this.fabClasses.set(Char.KayKitDungeonBanner, KayKitDungeonBannerFab);
        this.fabClasses.set(Char.KayKitDungeonBarrel, KayKitDungeonBarrelFab);
        this.fabClasses.set(Char.KayKitDungeonBarreldark, KayKitDungeonBarreldarkFab);
        this.fabClasses.set(Char.KayKitDungeonBench, KayKitDungeonBenchFab);
        this.fabClasses.set(Char.KayKitDungeonBooka, KayKitDungeonBookaFab);
        this.fabClasses.set(Char.KayKitDungeonBookb, KayKitDungeonBookbFab);
        this.fabClasses.set(Char.KayKitDungeonBookc, KayKitDungeonBookcFab);
        this.fabClasses.set(Char.KayKitDungeonBookd, KayKitDungeonBookdFab);
        this.fabClasses.set(Char.KayKitDungeonBooke, KayKitDungeonBookeFab);
        this.fabClasses.set(Char.KayKitDungeonBookf, KayKitDungeonBookfFab);
        this.fabClasses.set(Char.KayKitDungeonBookopena, KayKitDungeonBookopenaFab);
        this.fabClasses.set(Char.KayKitDungeonBookopenb, KayKitDungeonBookopenbFab);
        this.fabClasses.set(Char.KayKitDungeonBookcase, KayKitDungeonBookcaseFab);
        this.fabClasses.set(Char.KayKitDungeonBookcasefilled, KayKitDungeonBookcasefilledFab);
        this.fabClasses.set(Char.KayKitDungeonBookcasefilledBroken, KayKitDungeonBookcasefilledBrokenFab);
        this.fabClasses.set(Char.KayKitDungeonBookcasewide, KayKitDungeonBookcasewideFab);
        this.fabClasses.set(Char.KayKitDungeonBookcasewidefilled, KayKitDungeonBookcasewidefilledFab);
        this.fabClasses.set(Char.KayKitDungeonBookcasewidefilledBroken, KayKitDungeonBookcasewidefilledBrokenFab);
        this.fabClasses.set(Char.KayKitDungeonBookcasewideBroken, KayKitDungeonBookcasewideBrokenFab);
        this.fabClasses.set(Char.KayKitDungeonBookcaseBroken, KayKitDungeonBookcaseBrokenFab);
        this.fabClasses.set(Char.KayKitDungeonBricks, KayKitDungeonBricksFab);
        this.fabClasses.set(Char.KayKitDungeonBucket, KayKitDungeonBucketFab);
        this.fabClasses.set(Char.KayKitDungeonChair, KayKitDungeonChairFab);
        this.fabClasses.set(Char.KayKitDungeonChesttopCommon, KayKitDungeonChesttopCommonFab);
        this.fabClasses.set(Char.KayKitDungeonChesttopCommonEmpty, KayKitDungeonChesttopCommonEmptyFab);
        this.fabClasses.set(Char.KayKitDungeonChesttopRare, KayKitDungeonChesttopRareFab);
        this.fabClasses.set(Char.KayKitDungeonChesttopRareMimic, KayKitDungeonChesttopRareMimicFab);
        this.fabClasses.set(Char.KayKitDungeonChesttopUncommon, KayKitDungeonChesttopUncommonFab);
        this.fabClasses.set(Char.KayKitDungeonChesttopUncommonMimic, KayKitDungeonChesttopUncommonMimicFab);
        this.fabClasses.set(Char.KayKitDungeonChestCommon, KayKitDungeonChestCommonFab);
        this.fabClasses.set(Char.KayKitDungeonChestCommonEmpty, KayKitDungeonChestCommonEmptyFab);
        this.fabClasses.set(Char.KayKitDungeonChestRare, KayKitDungeonChestRareFab);
        this.fabClasses.set(Char.KayKitDungeonChestRareMimic, KayKitDungeonChestRareMimicFab);
        this.fabClasses.set(Char.KayKitDungeonChestUncommon, KayKitDungeonChestUncommonFab);
        this.fabClasses.set(Char.KayKitDungeonChestUncommonMimic, KayKitDungeonChestUncommonMimicFab);
        this.fabClasses.set(Char.KayKitDungeonCoin, KayKitDungeonCoinFab);
        this.fabClasses.set(Char.KayKitDungeonCoinslarge, KayKitDungeonCoinslargeFab);
        this.fabClasses.set(Char.KayKitDungeonCoinsmedium, KayKitDungeonCoinsmediumFab);
        this.fabClasses.set(Char.KayKitDungeonCoinssmall, KayKitDungeonCoinssmallFab);
        this.fabClasses.set(Char.KayKitDungeonCrate, KayKitDungeonCrateFab);
        this.fabClasses.set(Char.KayKitDungeonCratedark, KayKitDungeonCratedarkFab);
        this.fabClasses.set(Char.KayKitDungeonCrateplatformLarge, KayKitDungeonCrateplatformLargeFab);
        this.fabClasses.set(Char.KayKitDungeonCrateplatformMedium, KayKitDungeonCrateplatformMediumFab);
        this.fabClasses.set(Char.KayKitDungeonCrateplatformSmall, KayKitDungeonCrateplatformSmallFab);
        this.fabClasses.set(Char.KayKitDungeonCrossbowCommon, KayKitDungeonCrossbowCommonFab);
        this.fabClasses.set(Char.KayKitDungeonCrossbowRare, KayKitDungeonCrossbowRareFab);
        this.fabClasses.set(Char.KayKitDungeonCrossbowUncommon, KayKitDungeonCrossbowUncommonFab);
        this.fabClasses.set(Char.KayKitDungeonDaggerCommon, KayKitDungeonDaggerCommonFab);
        this.fabClasses.set(Char.KayKitDungeonDaggerRare, KayKitDungeonDaggerRareFab);
        this.fabClasses.set(Char.KayKitDungeonDaggerUncommon, KayKitDungeonDaggerUncommonFab);
        this.fabClasses.set(Char.KayKitDungeonDoor, KayKitDungeonDoorFab);
        this.fabClasses.set(Char.KayKitDungeonDoorGate, KayKitDungeonDoorGateFab);
        this.fabClasses.set(Char.KayKitDungeonFloordecorationShatteredbricks, KayKitDungeonFloordecorationShatteredbricksFab);
        this.fabClasses.set(Char.KayKitDungeonFloordecorationTileslarge, KayKitDungeonFloordecorationTileslargeFab);
        this.fabClasses.set(Char.KayKitDungeonFloordecorationTilessmall, KayKitDungeonFloordecorationTilessmallFab);
        this.fabClasses.set(Char.KayKitDungeonFloordecorationWood, KayKitDungeonFloordecorationWoodFab);
        this.fabClasses.set(Char.KayKitDungeonFloordecorationWoodleft, KayKitDungeonFloordecorationWoodleftFab);
        this.fabClasses.set(Char.KayKitDungeonFloordecorationWoodright, KayKitDungeonFloordecorationWoodrightFab);
        this.fabClasses.set(Char.KayKitDungeonHammerCommon, KayKitDungeonHammerCommonFab);
        this.fabClasses.set(Char.KayKitDungeonHammerRare, KayKitDungeonHammerRareFab);
        this.fabClasses.set(Char.KayKitDungeonHammerUncommon, KayKitDungeonHammerUncommonFab);
        this.fabClasses.set(Char.KayKitDungeonLootsacka, KayKitDungeonLootsackaFab);
        this.fabClasses.set(Char.KayKitDungeonLootsackb, KayKitDungeonLootsackbFab);
        this.fabClasses.set(Char.KayKitDungeonMug, KayKitDungeonMugFab);
        this.fabClasses.set(Char.KayKitDungeonPillar, KayKitDungeonPillarFab);
        this.fabClasses.set(Char.KayKitDungeonPillarBroken, KayKitDungeonPillarBrokenFab);
        this.fabClasses.set(Char.KayKitDungeonPlate, KayKitDungeonPlateFab);
        this.fabClasses.set(Char.KayKitDungeonPlatefull, KayKitDungeonPlatefullFab);
        this.fabClasses.set(Char.KayKitDungeonPlatehalf, KayKitDungeonPlatehalfFab);
        this.fabClasses.set(Char.KayKitDungeonPota, KayKitDungeonPotaFab);
        this.fabClasses.set(Char.KayKitDungeonPotaDecorated, KayKitDungeonPotaDecoratedFab);
        this.fabClasses.set(Char.KayKitDungeonPotb, KayKitDungeonPotbFab);
        this.fabClasses.set(Char.KayKitDungeonPotbDecorated, KayKitDungeonPotbDecoratedFab);
        this.fabClasses.set(Char.KayKitDungeonPotc, KayKitDungeonPotcFab);
        this.fabClasses.set(Char.KayKitDungeonPotcDecorated, KayKitDungeonPotcDecoratedFab);
        this.fabClasses.set(Char.KayKitDungeonPotionlargeBlue, KayKitDungeonPotionlargeBlueFab);
        this.fabClasses.set(Char.KayKitDungeonPotionlargeGreen, KayKitDungeonPotionlargeGreenFab);
        this.fabClasses.set(Char.KayKitDungeonPotionlargeRed, KayKitDungeonPotionlargeRedFab);
        this.fabClasses.set(Char.KayKitDungeonPotionmediumBlue, KayKitDungeonPotionmediumBlueFab);
        this.fabClasses.set(Char.KayKitDungeonPotionmediumGreen, KayKitDungeonPotionmediumGreenFab);
        this.fabClasses.set(Char.KayKitDungeonPotionmediumRed, KayKitDungeonPotionmediumRedFab);
        this.fabClasses.set(Char.KayKitDungeonPotionsmallBlue, KayKitDungeonPotionsmallBlueFab);
        this.fabClasses.set(Char.KayKitDungeonPotionsmallGreen, KayKitDungeonPotionsmallGreenFab);
        this.fabClasses.set(Char.KayKitDungeonPotionsmallRed, KayKitDungeonPotionsmallRedFab);
        this.fabClasses.set(Char.KayKitDungeonPots, KayKitDungeonPotsFab);
        this.fabClasses.set(Char.KayKitDungeonQuiverEmpty, KayKitDungeonQuiverEmptyFab);
        this.fabClasses.set(Char.KayKitDungeonQuiverFull, KayKitDungeonQuiverFullFab);
        this.fabClasses.set(Char.KayKitDungeonQuiverHalfFull, KayKitDungeonQuiverHalfFullFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldHigh, KayKitDungeonScaffoldHighFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldHighCornerboth, KayKitDungeonScaffoldHighCornerbothFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldHighCornerleft, KayKitDungeonScaffoldHighCornerleftFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldHighCornerright, KayKitDungeonScaffoldHighCornerrightFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldHighRailing, KayKitDungeonScaffoldHighRailingFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldLow, KayKitDungeonScaffoldLowFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldLowCornerboth, KayKitDungeonScaffoldLowCornerbothFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldLowCornerleft, KayKitDungeonScaffoldLowCornerleftFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldLowCornerright, KayKitDungeonScaffoldLowCornerrightFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldLowRailing, KayKitDungeonScaffoldLowRailingFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldMedium, KayKitDungeonScaffoldMediumFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldMediumCornerboth, KayKitDungeonScaffoldMediumCornerbothFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldMediumCornerleft, KayKitDungeonScaffoldMediumCornerleftFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldMediumCornerright, KayKitDungeonScaffoldMediumCornerrightFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldMediumRailing, KayKitDungeonScaffoldMediumRailingFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallHigh, KayKitDungeonScaffoldSmallHighFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallHighCornerleft, KayKitDungeonScaffoldSmallHighCornerleftFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallHighCornerright, KayKitDungeonScaffoldSmallHighCornerrightFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallHighLong, KayKitDungeonScaffoldSmallHighLongFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallHighRailing, KayKitDungeonScaffoldSmallHighRailingFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallHighRailingLong, KayKitDungeonScaffoldSmallHighRailingLongFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallLow, KayKitDungeonScaffoldSmallLowFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallLowCornerleft, KayKitDungeonScaffoldSmallLowCornerleftFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallLowCornerright, KayKitDungeonScaffoldSmallLowCornerrightFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallLowLong, KayKitDungeonScaffoldSmallLowLongFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallLowRailing, KayKitDungeonScaffoldSmallLowRailingFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallLowRailingLong, KayKitDungeonScaffoldSmallLowRailingLongFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallMedium, KayKitDungeonScaffoldSmallMediumFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallMediumCornerleft, KayKitDungeonScaffoldSmallMediumCornerleftFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallMediumCornerright, KayKitDungeonScaffoldSmallMediumCornerrightFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallMediumLong, KayKitDungeonScaffoldSmallMediumLongFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallMediumRailing, KayKitDungeonScaffoldSmallMediumRailingFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldSmallMediumRailingLong, KayKitDungeonScaffoldSmallMediumRailingLongFab);
        this.fabClasses.set(Char.KayKitDungeonScaffoldStairs, KayKitDungeonScaffoldStairsFab);
        this.fabClasses.set(Char.KayKitDungeonShieldCommon, KayKitDungeonShieldCommonFab);
        this.fabClasses.set(Char.KayKitDungeonShieldRare, KayKitDungeonShieldRareFab);
        this.fabClasses.set(Char.KayKitDungeonShieldUncommon, KayKitDungeonShieldUncommonFab);
        this.fabClasses.set(Char.KayKitDungeonSpellbook, KayKitDungeonSpellbookFab);
        this.fabClasses.set(Char.KayKitDungeonStaffCommon, KayKitDungeonStaffCommonFab);
        this.fabClasses.set(Char.KayKitDungeonStaffRare, KayKitDungeonStaffRareFab);
        this.fabClasses.set(Char.KayKitDungeonStaffUncommon, KayKitDungeonStaffUncommonFab);
        this.fabClasses.set(Char.KayKitDungeonStairs, KayKitDungeonStairsFab);
        this.fabClasses.set(Char.KayKitDungeonStairsWide, KayKitDungeonStairsWideFab);
        this.fabClasses.set(Char.KayKitDungeonStool, KayKitDungeonStoolFab);
        this.fabClasses.set(Char.KayKitDungeonSwordCommon, KayKitDungeonSwordCommonFab);
        this.fabClasses.set(Char.KayKitDungeonSwordRare, KayKitDungeonSwordRareFab);
        this.fabClasses.set(Char.KayKitDungeonSwordUncommon, KayKitDungeonSwordUncommonFab);
        this.fabClasses.set(Char.KayKitDungeonTablelarge, KayKitDungeonTablelargeFab);
        this.fabClasses.set(Char.KayKitDungeonTablemedium, KayKitDungeonTablemediumFab);
        this.fabClasses.set(Char.KayKitDungeonTablesmall, KayKitDungeonTablesmallFab);
        this.fabClasses.set(Char.KayKitDungeonTilebrickaLarge, KayKitDungeonTilebrickaLargeFab);
        this.fabClasses.set(Char.KayKitDungeonTilebrickaMedium, KayKitDungeonTilebrickaMediumFab);
        this.fabClasses.set(Char.KayKitDungeonTilebrickaSmall, KayKitDungeonTilebrickaSmallFab);
        this.fabClasses.set(Char.KayKitDungeonTilebrickbLarge, KayKitDungeonTilebrickbLargeFab);
        this.fabClasses.set(Char.KayKitDungeonTilebrickbLargecrackeda, KayKitDungeonTilebrickbLargecrackedaFab);
        this.fabClasses.set(Char.KayKitDungeonTilebrickbLargecrackedb, KayKitDungeonTilebrickbLargecrackedbFab);
        this.fabClasses.set(Char.KayKitDungeonTilebrickbMedium, KayKitDungeonTilebrickbMediumFab);
        this.fabClasses.set(Char.KayKitDungeonTilebrickbSmall, KayKitDungeonTilebrickbSmallFab);
        this.fabClasses.set(Char.KayKitDungeonTilespikes, KayKitDungeonTilespikesFab);
        this.fabClasses.set(Char.KayKitDungeonTilespikesLarge, KayKitDungeonTilespikesLargeFab);
        this.fabClasses.set(Char.KayKitDungeonTilespikesShallow, KayKitDungeonTilespikesShallowFab);
        this.fabClasses.set(Char.KayKitDungeonTorch, KayKitDungeonTorchFab);
        this.fabClasses.set(Char.KayKitDungeonTorchwall, KayKitDungeonTorchwallFab);
        this.fabClasses.set(Char.KayKitDungeonTrapdoor, KayKitDungeonTrapdoorFab);
        this.fabClasses.set(Char.KayKitDungeonWall, KayKitDungeonWallFab);
        this.fabClasses.set(Char.KayKitDungeonWallcorner, KayKitDungeonWallcornerFab);
        this.fabClasses.set(Char.KayKitDungeonWalldecorationa, KayKitDungeonWalldecorationaFab);
        this.fabClasses.set(Char.KayKitDungeonWalldecorationb, KayKitDungeonWalldecorationbFab);
        this.fabClasses.set(Char.KayKitDungeonWallintersection, KayKitDungeonWallintersectionFab);
        this.fabClasses.set(Char.KayKitDungeonWallsingle, KayKitDungeonWallsingleFab);
        this.fabClasses.set(Char.KayKitDungeonWallsingleBroken, KayKitDungeonWallsingleBrokenFab);
        this.fabClasses.set(Char.KayKitDungeonWallsingleCorner, KayKitDungeonWallsingleCornerFab);
        this.fabClasses.set(Char.KayKitDungeonWallsingleDecorationa, KayKitDungeonWallsingleDecorationaFab);
        this.fabClasses.set(Char.KayKitDungeonWallsingleDecorationb, KayKitDungeonWallsingleDecorationbFab);
        this.fabClasses.set(Char.KayKitDungeonWallsingleDoor, KayKitDungeonWallsingleDoorFab);
        this.fabClasses.set(Char.KayKitDungeonWallsingleSplit, KayKitDungeonWallsingleSplitFab);
        this.fabClasses.set(Char.KayKitDungeonWallsingleWindow, KayKitDungeonWallsingleWindowFab);
        this.fabClasses.set(Char.KayKitDungeonWallsingleWindowgate, KayKitDungeonWallsingleWindowgateFab);
        this.fabClasses.set(Char.KayKitDungeonWallsplit, KayKitDungeonWallsplitFab);
        this.fabClasses.set(Char.KayKitDungeonWallBroken, KayKitDungeonWallBrokenFab);
        this.fabClasses.set(Char.KayKitDungeonWallDoor, KayKitDungeonWallDoorFab);
        this.fabClasses.set(Char.KayKitDungeonWallEnd, KayKitDungeonWallEndFab);
        this.fabClasses.set(Char.KayKitDungeonWallEndBroken, KayKitDungeonWallEndBrokenFab);
        this.fabClasses.set(Char.KayKitDungeonWallGate, KayKitDungeonWallGateFab);
        this.fabClasses.set(Char.KayKitDungeonWallGatecorner, KayKitDungeonWallGatecornerFab);
        this.fabClasses.set(Char.KayKitDungeonWallGatedoor, KayKitDungeonWallGatedoorFab);
        this.fabClasses.set(Char.KayKitDungeonWallWindow, KayKitDungeonWallWindowFab);
        this.fabClasses.set(Char.KayKitDungeonWallWindowgate, KayKitDungeonWallWindowgateFab);
        this.fabClasses.set(Char.KayKitDungeonWeaponrack, KayKitDungeonWeaponrackFab);

        this.fabClasses.set(Char.CharAniQuaterniusZombieCharactersGermanshepherd, QuaterniusZombieCharactersGermanshepherdFab);
        this.fabClasses.set(Char.CharHumanQuaterniusZombieCharactersLis, QuaterniusZombieCharactersLisFab);
        this.fabClasses.set(Char.CharHumanQuaterniusZombieCharactersLisSingleweapon, QuaterniusZombieCharactersLisSingleweaponFab);
        this.fabClasses.set(Char.CharHumanQuaterniusZombieCharactersMatt, QuaterniusZombieCharactersMattFab);
        this.fabClasses.set(Char.CharHumanQuaterniusZombieCharactersMattSingleweapon, QuaterniusZombieCharactersMattSingleweaponFab);
        this.fabClasses.set(Char.CharAniQuaterniusZombieCharactersPug, QuaterniusZombieCharactersPugFab);
        this.fabClasses.set(Char.CharHumanQuaterniusZombieCharactersSam, QuaterniusZombieCharactersSamFab);
        this.fabClasses.set(Char.CharHumanQuaterniusZombieCharactersSamSingleweapon, QuaterniusZombieCharactersSamSingleweaponFab);
        this.fabClasses.set(Char.CharHumanQuaterniusZombieCharactersShaun, QuaterniusZombieCharactersShaunFab);
        this.fabClasses.set(Char.CharHumanQuaterniusZombieCharactersShaunSingleweapon, QuaterniusZombieCharactersShaunSingleweaponFab);
        this.fabClasses.set(Char.CharMonQuaterniusZombieZombieArm, QuaterniusZombieZombieArmFab);
        this.fabClasses.set(Char.CharMonQuaterniusZombieZombieBasic, QuaterniusZombieZombieBasicFab);
        this.fabClasses.set(Char.CharMonQuaterniusZombieZombieChubby, QuaterniusZombieZombieChubbyFab);
        this.fabClasses.set(Char.CharMonQuaterniusZombieZombieRibcage, QuaterniusZombieZombieRibcageFab);

        this.fabClasses.set(Char.QuaterniusNatureBushCommon, QuaterniusNatureBushCommonFab);
        this.fabClasses.set(Char.QuaterniusNatureBushCommonFlowers, QuaterniusNatureBushCommonFlowersFab);
        this.fabClasses.set(Char.QuaterniusNatureClover1, QuaterniusNatureClover1Fab);
        this.fabClasses.set(Char.QuaterniusNatureClover2, QuaterniusNatureClover2Fab);
        this.fabClasses.set(Char.QuaterniusNatureCommontree1, QuaterniusNatureCommontree1Fab);
        this.fabClasses.set(Char.QuaterniusNatureCommontree2, QuaterniusNatureCommontree2Fab);
        this.fabClasses.set(Char.QuaterniusNatureCommontree3, QuaterniusNatureCommontree3Fab);
        this.fabClasses.set(Char.QuaterniusNatureCommontree4, QuaterniusNatureCommontree4Fab);
        this.fabClasses.set(Char.QuaterniusNatureCommontree5, QuaterniusNatureCommontree5Fab);
        this.fabClasses.set(Char.QuaterniusNatureDeadtree1, QuaterniusNatureDeadtree1Fab);
        this.fabClasses.set(Char.QuaterniusNatureDeadtree2, QuaterniusNatureDeadtree2Fab);
        this.fabClasses.set(Char.QuaterniusNatureDeadtree3, QuaterniusNatureDeadtree3Fab);
        this.fabClasses.set(Char.QuaterniusNatureDeadtree4, QuaterniusNatureDeadtree4Fab);
        this.fabClasses.set(Char.QuaterniusNatureDeadtree5, QuaterniusNatureDeadtree5Fab);
        this.fabClasses.set(Char.QuaterniusNatureFern1, QuaterniusNatureFern1Fab);
        this.fabClasses.set(Char.QuaterniusNatureFlower3Group, QuaterniusNatureFlower3GroupFab);
        this.fabClasses.set(Char.QuaterniusNatureFlower3Single, QuaterniusNatureFlower3SingleFab);
        this.fabClasses.set(Char.QuaterniusNatureFlower4Group, QuaterniusNatureFlower4GroupFab);
        this.fabClasses.set(Char.QuaterniusNatureFlower4Single, QuaterniusNatureFlower4SingleFab);
        this.fabClasses.set(Char.QuaterniusNatureGrassCommonShort, QuaterniusNatureGrassCommonShortFab);
        this.fabClasses.set(Char.QuaterniusNatureGrassCommonTall, QuaterniusNatureGrassCommonTallFab);
        this.fabClasses.set(Char.QuaterniusNatureGrassWispyShort, QuaterniusNatureGrassWispyShortFab);
        this.fabClasses.set(Char.QuaterniusNatureGrassWispyTall, QuaterniusNatureGrassWispyTallFab);
        this.fabClasses.set(Char.QuaterniusNatureMushroomCommon, QuaterniusNatureMushroomCommonFab);
        this.fabClasses.set(Char.QuaterniusNatureMushroomLaetiporus, QuaterniusNatureMushroomLaetiporusFab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleRound1, QuaterniusNaturePebbleRound1Fab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleRound2, QuaterniusNaturePebbleRound2Fab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleRound3, QuaterniusNaturePebbleRound3Fab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleRound4, QuaterniusNaturePebbleRound4Fab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleRound5, QuaterniusNaturePebbleRound5Fab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleSquare1, QuaterniusNaturePebbleSquare1Fab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleSquare2, QuaterniusNaturePebbleSquare2Fab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleSquare3, QuaterniusNaturePebbleSquare3Fab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleSquare4, QuaterniusNaturePebbleSquare4Fab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleSquare5, QuaterniusNaturePebbleSquare5Fab);
        this.fabClasses.set(Char.QuaterniusNaturePebbleSquare6, QuaterniusNaturePebbleSquare6Fab);
        this.fabClasses.set(Char.QuaterniusNaturePetal1, QuaterniusNaturePetal1Fab);
        this.fabClasses.set(Char.QuaterniusNaturePetal2, QuaterniusNaturePetal2Fab);
        this.fabClasses.set(Char.QuaterniusNaturePetal3, QuaterniusNaturePetal3Fab);
        this.fabClasses.set(Char.QuaterniusNaturePetal4, QuaterniusNaturePetal4Fab);
        this.fabClasses.set(Char.QuaterniusNaturePetal5, QuaterniusNaturePetal5Fab);
        this.fabClasses.set(Char.QuaterniusNaturePine1, QuaterniusNaturePine1Fab);
        this.fabClasses.set(Char.QuaterniusNaturePine2, QuaterniusNaturePine2Fab);
        this.fabClasses.set(Char.QuaterniusNaturePine3, QuaterniusNaturePine3Fab);
        this.fabClasses.set(Char.QuaterniusNaturePine4, QuaterniusNaturePine4Fab);
        this.fabClasses.set(Char.QuaterniusNaturePine5, QuaterniusNaturePine5Fab);
        this.fabClasses.set(Char.QuaterniusNaturePlant1, QuaterniusNaturePlant1Fab);
        this.fabClasses.set(Char.QuaterniusNaturePlant1Big, QuaterniusNaturePlant1BigFab);
        this.fabClasses.set(Char.QuaterniusNaturePlant7, QuaterniusNaturePlant7Fab);
        this.fabClasses.set(Char.QuaterniusNaturePlant7Big, QuaterniusNaturePlant7BigFab);
        this.fabClasses.set(Char.QuaterniusNatureRockpathRoundSmall1, QuaterniusNatureRockpathRoundSmall1Fab);
        this.fabClasses.set(Char.QuaterniusNatureRockpathRoundSmall2, QuaterniusNatureRockpathRoundSmall2Fab);
        this.fabClasses.set(Char.QuaterniusNatureRockpathRoundSmall3, QuaterniusNatureRockpathRoundSmall3Fab);
        this.fabClasses.set(Char.QuaterniusNatureRockpathRoundThin, QuaterniusNatureRockpathRoundThinFab);
        this.fabClasses.set(Char.QuaterniusNatureRockpathRoundWide, QuaterniusNatureRockpathRoundWideFab);
        this.fabClasses.set(Char.QuaterniusNatureRockpathSquareSmall1, QuaterniusNatureRockpathSquareSmall1Fab);
        this.fabClasses.set(Char.QuaterniusNatureRockpathSquareSmall2, QuaterniusNatureRockpathSquareSmall2Fab);
        this.fabClasses.set(Char.QuaterniusNatureRockpathSquareSmall3, QuaterniusNatureRockpathSquareSmall3Fab);
        this.fabClasses.set(Char.QuaterniusNatureRockpathSquareThin, QuaterniusNatureRockpathSquareThinFab);
        this.fabClasses.set(Char.QuaterniusNatureRockpathSquareWide, QuaterniusNatureRockpathSquareWideFab);
        this.fabClasses.set(Char.QuaterniusNatureRockMedium1, QuaterniusNatureRockMedium1Fab);
        this.fabClasses.set(Char.QuaterniusNatureRockMedium2, QuaterniusNatureRockMedium2Fab);
        this.fabClasses.set(Char.QuaterniusNatureRockMedium3, QuaterniusNatureRockMedium3Fab);
        this.fabClasses.set(Char.QuaterniusNatureTwistedtree1, QuaterniusNatureTwistedtree1Fab);
        this.fabClasses.set(Char.QuaterniusNatureTwistedtree2, QuaterniusNatureTwistedtree2Fab);
        this.fabClasses.set(Char.QuaterniusNatureTwistedtree3, QuaterniusNatureTwistedtree3Fab);
        this.fabClasses.set(Char.QuaterniusNatureTwistedtree4, QuaterniusNatureTwistedtree4Fab);
        this.fabClasses.set(Char.QuaterniusNatureTwistedtree5, QuaterniusNatureTwistedtree5Fab);

        this.fabClasses.set(Char.QuaterniusCard0CardBack, QuaterniusCard0CardBackFab);
        this.fabClasses.set(Char.QuaterniusCard0CardContainer, QuaterniusCard0CardContainerFab);
        this.fabClasses.set(Char.QuaterniusCard0CardFront, QuaterniusCard0CardFrontFab);
        this.fabClasses.set(Char.QuaterniusCard0CardMask, QuaterniusCard0CardMaskFab);
        this.fabClasses.set(Char.QuaterniusCard10Beehive, QuaterniusCard10BeehiveFab);
        this.fabClasses.set(Char.QuaterniusCard11Polinization, QuaterniusCard11PolinizationFab);
        this.fabClasses.set(Char.QuaterniusCard12Mimic, QuaterniusCard12MimicFab);
        this.fabClasses.set(Char.QuaterniusCard13Seamonster, QuaterniusCard13SeamonsterFab);
        this.fabClasses.set(Char.QuaterniusCard14Coin, QuaterniusCard14CoinFab);
        this.fabClasses.set(Char.QuaterniusCard15Cult, QuaterniusCard15CultFab);
        this.fabClasses.set(Char.QuaterniusCard16Belltowers, QuaterniusCard16BelltowersFab);
        this.fabClasses.set(Char.QuaterniusCard17Rebirth, QuaterniusCard17RebirthFab);
        this.fabClasses.set(Char.QuaterniusCard18Waterdragon, QuaterniusCard18WaterdragonFab);
        this.fabClasses.set(Char.QuaterniusCard19Oceantreasure, QuaterniusCard19OceantreasureFab);
        this.fabClasses.set(Char.QuaterniusCard1Fireball, QuaterniusCard1FireballFab);
        this.fabClasses.set(Char.QuaterniusCard20ElementFire, QuaterniusCard20ElementFireFab);
        this.fabClasses.set(Char.QuaterniusCard21ElementLightning, QuaterniusCard21ElementLightningFab);
        this.fabClasses.set(Char.QuaterniusCard22ElementAir, QuaterniusCard22ElementAirFab);
        this.fabClasses.set(Char.QuaterniusCard23ElementWater, QuaterniusCard23ElementWaterFab);
        this.fabClasses.set(Char.QuaterniusCard24ElementDark, QuaterniusCard24ElementDarkFab);
        this.fabClasses.set(Char.QuaterniusCard25ElementEarth, QuaterniusCard25ElementEarthFab);
        this.fabClasses.set(Char.QuaterniusCard26Bloodring, QuaterniusCard26BloodringFab);
        this.fabClasses.set(Char.QuaterniusCard27Book, QuaterniusCard27BookFab);
        this.fabClasses.set(Char.QuaterniusCard28Rolldice, QuaterniusCard28RolldiceFab);
        this.fabClasses.set(Char.QuaterniusCard29Block, QuaterniusCard29BlockFab);
        this.fabClasses.set(Char.QuaterniusCard2Trenchcoatmushrooms, QuaterniusCard2TrenchcoatmushroomsFab);
        this.fabClasses.set(Char.QuaterniusCard30Wizard, QuaterniusCard30WizardFab);
        this.fabClasses.set(Char.QuaterniusCard3Monk, QuaterniusCard3MonkFab);
        this.fabClasses.set(Char.QuaterniusCard4Market, QuaterniusCard4MarketFab);
        this.fabClasses.set(Char.QuaterniusCard5Steal, QuaterniusCard5StealFab);
        this.fabClasses.set(Char.QuaterniusCard6King, QuaterniusCard6KingFab);
        this.fabClasses.set(Char.QuaterniusCard7Stinktrap, QuaterniusCard7StinktrapFab);
        this.fabClasses.set(Char.QuaterniusCard8Lightningwizard, QuaterniusCard8LightningwizardFab);
        this.fabClasses.set(Char.QuaterniusCard9Hypnosis, QuaterniusCard9HypnosisFab);

this.fabClasses.set(Char.QuaterniusAniCharBasecharacter, QuaterniusAniCharBasecharacterFab);
this.fabClasses.set(Char.QuaterniusAniCharBluesoldierFemale, QuaterniusAniCharBluesoldierFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharBluesoldierMale, QuaterniusAniCharBluesoldierMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharCasual2Female, QuaterniusAniCharCasual2FemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharCasual2Male, QuaterniusAniCharCasual2MaleFab);
this.fabClasses.set(Char.QuaterniusAniCharCasual3Female, QuaterniusAniCharCasual3FemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharCasual3Male, QuaterniusAniCharCasual3MaleFab);
this.fabClasses.set(Char.QuaterniusAniCharCasualBald, QuaterniusAniCharCasualBaldFab);
this.fabClasses.set(Char.QuaterniusAniCharCasualFemale, QuaterniusAniCharCasualFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharCasualMale, QuaterniusAniCharCasualMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharChefFemale, QuaterniusAniCharChefFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharChefHat, QuaterniusAniCharChefHatFab);
this.fabClasses.set(Char.QuaterniusAniCharChefMale, QuaterniusAniCharChefMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharCow, QuaterniusAniCharCowFab);
this.fabClasses.set(Char.QuaterniusAniCharCowboyFemale, QuaterniusAniCharCowboyFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharCowboyHair, QuaterniusAniCharCowboyHairFab);
this.fabClasses.set(Char.QuaterniusAniCharCowboyMale, QuaterniusAniCharCowboyMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharDoctorFemaleOld, QuaterniusAniCharDoctorFemaleOldFab);
this.fabClasses.set(Char.QuaterniusAniCharDoctorFemaleYoung, QuaterniusAniCharDoctorFemaleYoungFab);
this.fabClasses.set(Char.QuaterniusAniCharDoctorMaleOld, QuaterniusAniCharDoctorMaleOldFab);
this.fabClasses.set(Char.QuaterniusAniCharDoctorMaleYoung, QuaterniusAniCharDoctorMaleYoungFab);
this.fabClasses.set(Char.QuaterniusAniCharElf, QuaterniusAniCharElfFab);
this.fabClasses.set(Char.QuaterniusAniCharGoblinFemale, QuaterniusAniCharGoblinFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharGoblinMale, QuaterniusAniCharGoblinMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharKimonoFemale, QuaterniusAniCharKimonoFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharKimonoMale, QuaterniusAniCharKimonoMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharKnightGoldenFemale, QuaterniusAniCharKnightGoldenFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharKnightGoldenMale, QuaterniusAniCharKnightGoldenMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharKnightMale, QuaterniusAniCharKnightMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharNinjaFemale, QuaterniusAniCharNinjaFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharNinjaMale, QuaterniusAniCharNinjaMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharNinjaMaleHair, QuaterniusAniCharNinjaMaleHairFab);
this.fabClasses.set(Char.QuaterniusAniCharNinjaSand, QuaterniusAniCharNinjaSandFab);
this.fabClasses.set(Char.QuaterniusAniCharNinjaSandFemale, QuaterniusAniCharNinjaSandFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharOldclassyFemale, QuaterniusAniCharOldclassyFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharOldclassyMale, QuaterniusAniCharOldclassyMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharPirateFemale, QuaterniusAniCharPirateFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharPirateMale, QuaterniusAniCharPirateMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharPug, QuaterniusAniCharPugFab);
this.fabClasses.set(Char.QuaterniusAniCharSoldierFemale, QuaterniusAniCharSoldierFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharSoldierMale, QuaterniusAniCharSoldierMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharSuitFemale, QuaterniusAniCharSuitFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharSuitMale, QuaterniusAniCharSuitMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharVikinghelmet, QuaterniusAniCharVikinghelmetFab);
this.fabClasses.set(Char.QuaterniusAniCharVikingFemale, QuaterniusAniCharVikingFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharVikingMale, QuaterniusAniCharVikingMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharWitch, QuaterniusAniCharWitchFab);
this.fabClasses.set(Char.QuaterniusAniCharWizard, QuaterniusAniCharWizardFab);
this.fabClasses.set(Char.QuaterniusAniCharWorkerFemale, QuaterniusAniCharWorkerFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharWorkerMale, QuaterniusAniCharWorkerMaleFab);
this.fabClasses.set(Char.QuaterniusAniCharZombieFemale, QuaterniusAniCharZombieFemaleFab);
this.fabClasses.set(Char.QuaterniusAniCharZombieMale, QuaterniusAniCharZombieMaleFab);

    }

    GetAssets(id: Char): IAsset {
        if (!this.fabInstances.has(id)) {
            const FabClass = this.fabClasses.get(id);
            if (!FabClass) {
                console.warn(`Fab class for ${id} not found. Using default MaleFab.`);
                return this.GetAssets(Char.CharHumanMale);
            }
            const instance = new FabClass(this);
            this.fabInstances.set(id, instance);
        }
        return this.fabInstances.get(id)!;
    }

    get Load(): GLTFLoader {
        return this.loader;
    }

    get LoadingManager(): THREE.LoadingManager {
        return this.loadingManager;
    }

    get FBXLoader(): FBXLoader {
        return this.fbxLoader;
    }
}
