import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { FBXLoader } from "three/examples/jsm/loaders/FBXLoader.js";
import { IAsset } from "./iasset";
import { Char } from "./assettypes";
import { DeadtreeFab } from "./plant/deadtreefab";
import { MaleFab } from "./malefab";
import { FemaleFab } from "./femalefab";
import { MushroomFab } from "./plant/mushroomfab";
import { DeadTree2Fab, TreeFab } from "./plant/treefab";
import { PortalFab } from "./portalfab";
import { TestFab } from "./testfab";
import { ZombieFab } from "./monster/zombiefab";
import { BatFab } from "./item/batfab";
import { GunFab } from "./item/gunfab";
import { MinataurFab } from "./monster/minataurfab";
import { CrabFab } from "./monster/crabfab";
import { StoneFab } from "./stonefab";
import { HammerFab, WarteringCanFab } from "./plant/farmtoolsfab";
import { BedFab, ClosetFab, DeskFab } from "./furniture/funiturefab";
import { AppleTreeFab, CoconutTreeFab } from "./plant/plantfab";
import { BatPigFab } from "./monster/batpigfab";
import { BirdMonFab } from "./monster/birdmonfab";
import { BilbyFab } from "./pet/bilbyfab";
import { WereWolfFab } from "./monster/werewolffab";
import { BigGolemFab, GolemFab } from "./monster/golemfab";
import { SnakeFab } from "./monster/snakefab";
import { VikingFab } from "./monster/vikingfab";
import { BuilderFab } from "./monster/builderfab";
import { ToadMageFab } from "./monster/toadmagefab";
import { KittenMonkFab } from "./monster/kittenmonk";
import { SkeletonFab } from "./monster/skeleton";
import { Tomato0Fab, Tomato1Fab, Tomato2Fab } from "./plant/tomatofab";
import { Carrot0Fab, Carrot1Fab, Carrot2Fab } from "./plant/carrotfab";
import { Potato0Fab, Potato1Fab, Potato2Fab } from "./plant/potatofab";
import { BathFab, SinkFab, ToiletFab } from "./furniture/bathfab";
import { BookShelfFab, TableFab, TvFab } from "./furniture/livingfab";
import { KitTableFab, KitchenFab, OvenFab, RefrigeratorFab } from "./furniture/kitchenfab";
import { AppleFab, CoconutFab } from "./plant/fruitfab";
import { DogFab } from "./pet/dogfab";
import { PetSnakeFab } from "./pet/animalpackfab";
import { BeeFab } from "./pet/bee";
import { EmptyFab } from "./emptyfab";
import { HellBoyFab } from "./hellboy";
import { CuteGirlFab } from "./cutegirl";
import { OfficeGirlFab } from "./officegirl";
import { WizardFab } from "./wizardfab";
import { TwoBFab } from "./twobfab";
import { ArrowFab } from "./arrowfab";
import { GrassFab } from "./plant/grassfab";
import { FluffyTreeFab } from "./plant/fluffytree";
import { CatFab } from "./pet/catfab";
import { KayKitSkeletonAXeFab, KayKitSkeletonArrowBrokenFab, KayKitSkeletonArrowBrokenHalfFab, KayKitSkeletonArrowFab, KayKitSkeletonArrowHalfFab, KayKitSkeletonBladeFab, KayKitSkeletonCrossbowFab, KayKitSkeletonQuiverFab, KayKitSkeletonShieldLargeAFab, KayKitSkeletonShieldLargeBFab, KayKitSkeletonShieldSmallAFab, KayKitSkeletonShieldSmallBFab, KayKitSkeletonStaffFab } from "./kaykit/items/skeletonsitems";
import { KayKitSkeletonMageFab, KayKitSkeletonMinionFab, KayKitSkeletonRogueFab, KayKitSkeletonWarriorFab } from "./kaykit/skeletons/skeletons";
import { KayKitAdvBarbarianFab, KayKitAdvKnightFab, KayKitAdvMageFab, KayKitAdvRogueFab, KayKitAdvRogueHoodedFab } from "./kaykit/adventuerers/adventurers";
import { KayKitArrowBundleFab, KayKitArrowFab, KayKitAxe1HandedFab, KayKitAxe2HandedFab, KayKitCrossbow1HandedFab, KayKitCrossbow2HandedFab, KayKitDaggerFab, KayKitMugEmptyFab, KayKitMugFullFab, KayKitQuiverFab, KayKitShieldBadgeColorFab, KayKitShieldBadgeFab, KayKitShieldRoundBarbarianFab, KayKitShieldRoundColorFab, KayKitShieldRoundFab, KayKitShieldSpikesColorFab, KayKitShieldSpikesFab, KayKitShieldSquareColorFab, KayKitShieldSquareFab, KayKitSmokeBombFab, KayKitSpellbookClosedFab, KayKitSpellbookOpenFab, KayKitStaffFab, KayKitSword1HandedFab, KayKitSword2HandedColorFab, KayKitSword2HandedFab, KayKitWandFab } from "./kaykit/items/advitems";
import { OceanStarterAnemonieFab, OceanStarterChestFab, OceanStarterChestOldFab, OceanStarterCrashedShipFab, OceanStarterLongPlantFab, OceanStarterPirateShipFab, OceanStarterSmallBoatFab, OceanStarterSmallCoralFab, OceanStarterSubmarineFab } from "./oceanpack/oceanpack";
import { EasypackFrogFab, EasypackRatFab, EasypackSlimeFab, EasypackSnakeAngryFab, EasypackSnakeFab, EasypackSpiderFab, EasypackWaspFab } from "./monster/easypack";
import { OceanDolphinFab, OceanFish1Fab, OceanFish2Fab, OceanFish3Fab, OceanMantaRayFab, OceanSharkFab, OceanWhaleFab } from "./oceanpack/oceananimalfab";
import { UltimateCharFab, UltimateCharGunFab } from "./ultimatepack/charactersfab";
import { UltimateCubeBricksFab, UltimateCubeCrateFab, UltimateCubeDefaultFab, UltimateCubeDirtSingleFab, UltimateCubeExclamationFab, UltimateCubeGrassSingleFab, UltimateCubeQuestionFab } from "./ultimatepack/cubefab";
import { UltimateEnermyBeeFab, UltimateEnermyCrabFab, UltimateEnermyFab, UltimateEnermySkullFab } from "./ultimatepack/enermyfab";
import { UltimateLvAndMaArrowFab, UltimateLvAndMaArrowSideFab, UltimateLvAndMaArrowUpFab, UltimateLvAndMaBombFab, UltimateLvAndMaBouncerFab, UltimateLvAndMaBridgeModularCenterFab, UltimateLvAndMaBridgeModularFab, UltimateLvAndMaBridgeSmallFab, UltimateLvAndMaCannonBallFab, UltimateLvAndMaCannonFab, UltimateLvAndMaChestFab, UltimateLvAndMaDoorFab, UltimateLvAndMaFence1Fab, UltimateLvAndMaFenceCornerFab, UltimateLvAndMaFenceMiddleFab, UltimateLvAndMaGoalFlagFab, UltimateLvAndMaHazardCylinderFab, UltimateLvAndMaHazardSawFab, UltimateLvAndMaHazardSpikeTrapFab, UltimateLvAndMaLeverFab, UltimateLvAndMaNumber0Fab, UltimateLvAndMaNumber1Fab, UltimateLvAndMaNumber2Fab, UltimateLvAndMaNumber3Fab, UltimateLvAndMaNumber4Fab, UltimateLvAndMaNumber5Fab, UltimateLvAndMaNumber6Fab, UltimateLvAndMaNumber7Fab, UltimateLvAndMaNumber8Fab, UltimateLvAndMaNumber9Fab, UltimateLvAndMaPipe90Fab, UltimateLvAndMaPipeEndFab, UltimateLvAndMaPipeStraightFab, UltimateLvAndMaPipeTFab, UltimateLvAndMaPlantLargeFab, UltimateLvAndMaPlantSmallFab, UltimateLvAndMaSpikesFab, UltimateLvAndMaSpikyBallFab, UltimateLvAndMaStairsFab, UltimateLvAndMaStairsModularEndFab, UltimateLvAndMaStairsModularMiddleFab, UltimateLvAndMaStairsModularStartFab, UltimateLvAndMaStairsSmallFab, UltimateLvAndMaTowerFab } from "./ultimatepack/lvandmachinefab";
import { UltimateModPlatform2DCubeDirt1x1CenterFab, UltimateModPlatform2DCubeDirt1x1EndFab, UltimateModPlatform2DCubeGrass1x1CenterFab, UltimateModPlatform2DCubeGrass1x1EndFab, UltimateModPlatform3DCubeDirtCenterTallFab, UltimateModPlatform3DCubeDirtCornerTallFab, UltimateModPlatform3DCubeDirtSideTallFab, UltimateModPlatform3DCubeGrassBottomTallFab, UltimateModPlatform3DCubeGrassCornerBottomTallFab, UltimateModPlatform3DCubeGrassCornerCenterTallFab, UltimateModPlatform3DCubeGrassCornerTallFab, UltimateModPlatform3DCubeGrassSideBottomTallFab, UltimateModPlatform3DCubeGrassSideCenterTallFab, UltimateModPlatform3DCubeGrassSideTallFab, UltimateModPlatformSingleCubeDirtFab, UltimateModPlatformSingleCubeGrassFab, UltimateModPlatformSingleHeightDirtCenterFab, UltimateModPlatformSingleHeightDirtCornerFab, UltimateModPlatformSingleHeightDirtSideFab, UltimateModPlatformSingleHeightGrassCenterFab, UltimateModPlatformSingleHeightGrassCornerFab, UltimateModPlatformSingleHeightGrassSideFab } from "./ultimatepack/modplatformfab";
import { UltimateNatureBushFab, UltimateNatureBushFruitFab, UltimateNatureCloud1Fab, UltimateNatureCloud2Fab, UltimateNatureCloud3Fab, UltimateNatureFruitFab, UltimateNatureGrass1Fab, UltimateNatureGrass2Fab, UltimateNatureGrass3Fab, UltimateNatureRock1Fab, UltimateNatureRock2Fab, UltimateNatureRockPlatformTallFab, UltimateNatureRockPlatforms1Fab, UltimateNatureRockPlatforms2Fab, UltimateNatureRockPlatforms3Fab, UltimateNatureRockPlatformsLargeFab, UltimateNatureRockPlatformsMediumFab, UltimateNatureTreeFab, UltimateNatureTreeFruitFab } from "./ultimatepack/naturefab";
import { UltimatePAPCoinFab, UltimatePAPGemBlueFab, UltimatePAPGemGreenFab, UltimatePAPGemPinkFab, UltimatePAPHeartFab, UltimatePAPHeartHalfFab, UltimatePAPHeartOutlineFab, UltimatePAPKeyFab, UltimatePAPStarFab, UltimatePAPStarOutlineFab, UltimatePAPThunderFab } from "./ultimatepack/powerpickupfab";
import { FarmPetCowFab, FarmPetHorseFab, FarmPetLlamaFab, FarmPetPigFab, FarmPetPugFab, FarmPetSheepFab, FarmPetZebraFab } from "./pet/farmanimalfab";
import { FoxishFab } from "./monster/foxishfab";
import { PantherBlackWhiteFab, PantherBlueFab, PantherRedFab } from "./monster/pantherfab";
import { KenneyCriminalMaleFab, KenneyCyborgFemaleFab, KenneyHumanFemaleFab, KenneyHumanMaleFab, KenneySkaterFemaleFab, KenneySkaterMaleFab, KenneySurvivorFemaleFab, KenneySurvivorMaleFab, KenneyZombieAFab, KenneyZombieBFab, KenneyZombieFemaleAFab, KenneyZombieFemaleBFab } from "./kenney/charactersfab";
import { KayKitDungeoncrossbowrareFab, KayKitDungeonscaffoldsmallmediumcornerRightFab, KayKitDungeonscaffoldlowcornerRightFab, KayKitDungeonscaffoldsmallmediumlongFab, KayKitDungeoncrateDarkFab, KayKitDungeonaxeDoubleuncommonFab, KayKitDungeonfloorDecorationwoodLeftFab, KayKitDungeonscaffoldsmallmediumcornerLeftFab, KayKitDungeonlootSackAFab, KayKitDungeonbookcasebrokenFab, KayKitDungeonplateFullFab, KayKitDungeoncoinsLargeFab, KayKitDungeonpotionMediumgreenFab, KayKitDungeonscaffoldsmalllowcornerLeftFab, KayKitDungeonbookcaseFilledFab, KayKitDungeonscaffoldhighrailingFab, KayKitDungeonwallbrokenFab, KayKitDungeonchestuncommonFab, KayKitDungeonpotionMediumredFab, KayKitDungeonwallDecorationAFab, KayKitDungeonpotBFab, KayKitDungeonwallgateDoorFab, KayKitDungeonhammeruncommonFab, KayKitDungeonscaffoldmediumrailingFab, KayKitDungeonwallgateFab, KayKitDungeonwalldoorFab, KayKitDungeonpotionLargeblueFab, KayKitDungeonscaffoldlowcornerBothFab, KayKitDungeonbookcaseWidebrokenFab, KayKitDungeonscaffoldsmallhighcornerLeftFab, KayKitDungeonscaffoldmediumcornerLeftFab, KayKitDungeonfloorDecorationwoodRightFab, KayKitDungeontorchFab, KayKitDungeonscaffoldsmallhighFab, KayKitDungeonscaffoldmediumcornerBothFab, KayKitDungeonchestcommonemptyFab, KayKitDungeonbookAFab, KayKitDungeonbookFFab, KayKitDungeonartifactFab, KayKitDungeontorchWallFab, KayKitDungeonwallSingleFab, KayKitDungeonwallSinglewindowFab, KayKitDungeonaxeuncommonFab, KayKitDungeonbarrelFab, KayKitDungeonpotionMediumblueFab, KayKitDungeonscaffoldsmallhighrailinglongFab, KayKitDungeonscaffoldmediumFab, KayKitDungeoncratePlatformmediumFab, KayKitDungeonwallSingledecorationBFab, KayKitDungeonaxecommonFab, KayKitDungeonpotCdecoratedFab, KayKitDungeonbookEFab, KayKitDungeondoorFab, KayKitDungeondoorgateFab, KayKitDungeonwallSinglecornerFab, KayKitDungeonpotionLargeredFab, KayKitDungeonscaffoldsmallhighcornerRightFab, KayKitDungeonwallSinglesplitFab, KayKitDungeonchestraremimicFab, KayKitDungeoncrateFab, KayKitDungeonbucketFab, KayKitDungeonaxerareFab, KayKitDungeonstaffuncommonFab, KayKitDungeonshieldcommonFab, KayKitDungeonscaffoldhighcornerBothFab, KayKitDungeonpotionLargegreenFab, KayKitDungeonbookCFab, KayKitDungeonwallSinglebrokenFab, KayKitDungeonfloorDecorationtilesLargeFab, KayKitDungeonbookcaseWideFab, KayKitDungeonpotionSmallgreenFab, KayKitDungeonscaffoldhighFab, KayKitDungeonhammercommonFab, KayKitDungeonwallendbrokenFab, KayKitDungeonwallSingledecorationAFab, KayKitDungeonquiveremptyFab, KayKitDungeonbookDFab, KayKitDungeonpillarFab, KayKitDungeonscaffoldhighcornerRightFab, KayKitDungeonweaponRackFab, KayKitDungeonbookOpenBFab, KayKitDungeontableSmallFab, KayKitDungeonaxeDoublecommonFab, KayKitDungeonbarrelDarkFab, KayKitDungeonwallCornerFab, KayKitDungeonscaffoldsmalllowrailingFab, KayKitDungeonswordcommonFab, KayKitDungeonaxeDoublerareFab, KayKitDungeonpotsFab, KayKitDungeonfloorDecorationshatteredBricksFab, KayKitDungeonquiverfullFab, KayKitDungeonscaffoldsmallhighrailingFab, KayKitDungeonstaffcommonFab, KayKitDungeonscaffoldsmalllowFab, KayKitDungeontableLargeFab, KayKitDungeonchestTopraremimicFab, KayKitDungeoncratePlatformsmallFab, KayKitDungeoncrossbowcommonFab, KayKitDungeontileBrickBsmallFab, KayKitDungeonwallSingledoorFab, KayKitDungeonpillarbrokenFab, KayKitDungeonshieldrareFab, KayKitDungeonbookcaseFab, KayKitDungeonscaffoldsmallmediumrailinglongFab, KayKitDungeonwallgateCornerFab, KayKitDungeonscaffoldhighcornerLeftFab, KayKitDungeonstairswideFab, KayKitDungeonbannerFab, KayKitDungeonstairsFab, KayKitDungeontileBrickBmediumFab, KayKitDungeoncoinsSmallFab, KayKitDungeonshielduncommonFab, KayKitDungeontileSpikeslargeFab, KayKitDungeonbenchFab, KayKitDungeonchestuncommonmimicFab, KayKitDungeonstaffrareFab, KayKitDungeonchestTopcommonemptyFab, KayKitDungeonbookOpenAFab, KayKitDungeonhammerrareFab, KayKitDungeonpotAdecoratedFab, KayKitDungeonbricksFab, KayKitDungeonbookBFab, KayKitDungeonspellBookFab, KayKitDungeontileBrickBlargeCrackedBFab, KayKitDungeonchestcommonFab, KayKitDungeonbookcaseWideFilledbrokenFab, KayKitDungeonlootSackBFab, KayKitDungeonfloorDecorationwoodFab, KayKitDungeonmugFab, KayKitDungeontileBrickAmediumFab, KayKitDungeonpotCFab, KayKitDungeondaggercommonFab, KayKitDungeonchestrareFab, KayKitDungeondaggerrareFab, KayKitDungeonscaffoldsmallmediumrailingFab, KayKitDungeonplateFab, KayKitDungeonscaffoldmediumcornerRightFab, KayKitDungeonstoolFab, KayKitDungeonswordrareFab, KayKitDungeonscaffoldstairsFab, KayKitDungeontileBrickBlargeCrackedAFab, KayKitDungeonchestTopuncommonFab, KayKitDungeontileBrickAlargeFab, KayKitDungeonwallIntersectionFab, KayKitDungeonpotionSmallblueFab, KayKitDungeonwallFab, KayKitDungeonwallSplitFab, KayKitDungeonscaffoldsmallmediumFab, KayKitDungeonplateHalfFab, KayKitDungeonscaffoldsmalllowlongFab, KayKitDungeonfloorDecorationtilesSmallFab, KayKitDungeonpotionSmallredFab, KayKitDungeonwallSinglewindowGateFab, KayKitDungeontileSpikesshallowFab, KayKitDungeonwallDecorationBFab, KayKitDungeonscaffoldlowrailingFab, KayKitDungeonscaffoldlowFab, KayKitDungeoncratePlatformlargeFab, KayKitDungeonwallwindowFab, KayKitDungeonscaffoldsmalllowrailinglongFab, KayKitDungeoncoinFab, KayKitDungeonchestTopuncommonmimicFab, KayKitDungeonpotAFab, KayKitDungeontileBrickBlargeFab, KayKitDungeonscaffoldsmalllowcornerRightFab, KayKitDungeonchairFab, KayKitDungeonscaffoldsmallhighlongFab, KayKitDungeonarrowFab, KayKitDungeonquiverhalffullFab, KayKitDungeoncoinsMediumFab, KayKitDungeonscaffoldlowcornerLeftFab, KayKitDungeonbookcaseFilledbrokenFab, KayKitDungeonwallendFab, KayKitDungeontableMediumFab, KayKitDungeonbookcaseWideFilledFab, KayKitDungeoncrossbowuncommonFab, KayKitDungeonsworduncommonFab, KayKitDungeonpotBdecoratedFab, KayKitDungeontileBrickAsmallFab, KayKitDungeonchestToprareFab, KayKitDungeondaggeruncommonFab, KayKitDungeontileSpikesFab, KayKitDungeonwallwindowGateFab, KayKitDungeonchestTopcommonFab, KayKitDungeontrapdoorFab,  } from "./kaykit/dungeon_pack/dungeonfab";


// Fab 클래스 타입
type FabConstructor = new (loader: Loader, ...args: any[]) => IAsset;

export class Loader {
    private fbxLoader = new FBXLoader();
    private loadingManager = new THREE.LoadingManager();
    private loader = new GLTFLoader(this.loadingManager);

    fabClasses = new Map<Char, FabConstructor>();
    private fabInstances = new Map<Char, IAsset>();

    constructor(public rootPath: string = "https://hons.ghostwebservice.com/") {
        THREE.Cache.enabled = true;

        this.registerFabs();
    }

    private registerFabs() {
        // 모든 Fab 클래스 등록 (생략 없이)
        this.fabClasses.set(Char.CharHumanMale, MaleFab);
        this.fabClasses.set(Char.CharHumanFemale, FemaleFab);
        this.fabClasses.set(Char.CharMonHellboy, HellBoyFab);
        this.fabClasses.set(Char.CharHumanCuteGirl, CuteGirlFab);
        this.fabClasses.set(Char.CharHumanOfficeGirl, OfficeGirlFab);
        this.fabClasses.set(Char.CharHumanWizard, WizardFab);
        this.fabClasses.set(Char.CharHumanTwoB, TwoBFab);
        this.fabClasses.set(Char.Arrow, ArrowFab);

        this.fabClasses.set(Char.Mushroom1, MushroomFab);
        this.fabClasses.set(Char.Mushroom2, MushroomFab);
        this.fabClasses.set(Char.Tree, TreeFab);
        this.fabClasses.set(Char.DeadTree, DeadtreeFab);
        this.fabClasses.set(Char.Portal, PortalFab);
        this.fabClasses.set(Char.Test, TestFab);

        // Kenney
        this.fabClasses.set(Char.CharHumanKenneyCriminalMale, KenneyCriminalMaleFab);
        this.fabClasses.set(Char.CharHumanKenneyCyborgFemale, KenneyCyborgFemaleFab);
        this.fabClasses.set(Char.CharHumanKenneyHumanFemale, KenneyHumanFemaleFab);
        this.fabClasses.set(Char.CharHumanKenneyHumanMale, KenneyHumanMaleFab);
        this.fabClasses.set(Char.CharHumanKenneySkaterFemale, KenneySkaterFemaleFab);
        this.fabClasses.set(Char.CharHumanKenneySkaterMale, KenneySkaterMaleFab);
        this.fabClasses.set(Char.CharHumanKenneySurvivorFemale, KenneySurvivorFemaleFab);
        this.fabClasses.set(Char.CharHumanKenneySurvivorMale, KenneySurvivorMaleFab);
        this.fabClasses.set(Char.CharMonKenneyZombieA, KenneyZombieAFab);
        this.fabClasses.set(Char.CharMonKenneyZombieB, KenneyZombieBFab);
        this.fabClasses.set(Char.CharMonKenneyZombieFemaleA, KenneyZombieFemaleAFab);
        this.fabClasses.set(Char.CharMonKenneyZombieFemaleB, KenneyZombieFemaleBFab);

        // Monster
        this.fabClasses.set(Char.CharMonZombie, ZombieFab);
        this.fabClasses.set(Char.CharMonMinataur, MinataurFab);
        this.fabClasses.set(Char.CharMonCrab, CrabFab);
        this.fabClasses.set(Char.CharMonBatPig, BatPigFab);
        this.fabClasses.set(Char.CharMonBird, BirdMonFab);
        this.fabClasses.set(Char.CharMonWereWolf, WereWolfFab);
        this.fabClasses.set(Char.CharMonGolem, GolemFab);
        this.fabClasses.set(Char.CharMonBigGolem, BigGolemFab);
        this.fabClasses.set(Char.CharMonSnake, SnakeFab);
        this.fabClasses.set(Char.CharHumanViking, VikingFab);
        this.fabClasses.set(Char.CharHumanBuilder, BuilderFab);
        this.fabClasses.set(Char.CharMonToadMage, ToadMageFab);
        this.fabClasses.set(Char.CharMonKittenMonk, KittenMonkFab);
        this.fabClasses.set(Char.CharMonSkeleton, SkeletonFab);
        this.fabClasses.set(Char.CharAniFoxish, FoxishFab);
        this.fabClasses.set(Char.CharMonPantherBlackWhite, PantherBlackWhiteFab);
        this.fabClasses.set(Char.CharMonPantherBlue, PantherBlueFab);
        this.fabClasses.set(Char.CharAniPantherRed, PantherRedFab);

        // KayKit
        this.fabClasses.set(Char.CharMonKayKitSkeletonMage, KayKitSkeletonMageFab);
        this.fabClasses.set(Char.CharMonKayKitSkeletonWarrior, KayKitSkeletonWarriorFab);
        this.fabClasses.set(Char.CharMonKayKitSkeletonRogue, KayKitSkeletonRogueFab);
        this.fabClasses.set(Char.CharMonKayKitSkeletonMinion, KayKitSkeletonMinionFab);

        this.fabClasses.set(Char.KayKitSkeletonArrow, KayKitSkeletonArrowFab);
        this.fabClasses.set(Char.KayKitSkeletonArrowBroken, KayKitSkeletonArrowBrokenFab);
        this.fabClasses.set(Char.KayKitSkeletonArrowBrokenHalf, KayKitSkeletonArrowBrokenHalfFab);
        this.fabClasses.set(Char.KayKitSkeletonArrowHalf, KayKitSkeletonArrowHalfFab);
        this.fabClasses.set(Char.KayKitSkeletonAxe, KayKitSkeletonAXeFab);
        this.fabClasses.set(Char.KayKitSkeletonBlade, KayKitSkeletonBladeFab);
        this.fabClasses.set(Char.KayKitSkeletonCrossbow, KayKitSkeletonCrossbowFab);
        this.fabClasses.set(Char.KayKitSkeletonQuiver, KayKitSkeletonQuiverFab);
        this.fabClasses.set(Char.KayKitSkeletonShieldLarge_A, KayKitSkeletonShieldLargeAFab);
        this.fabClasses.set(Char.KayKitSkeletonShieldLarge_B, KayKitSkeletonShieldLargeBFab);
        this.fabClasses.set(Char.KayKitSkeletonShieldSmall_A, KayKitSkeletonShieldSmallAFab);
        this.fabClasses.set(Char.KayKitSkeletonShieldSmall_B, KayKitSkeletonShieldSmallBFab);
        this.fabClasses.set(Char.KayKitSkeletonStaff, KayKitSkeletonStaffFab);

        this.fabClasses.set(Char.CharHumanKayKitAdvBarbarian, KayKitAdvBarbarianFab);
        this.fabClasses.set(Char.CharHumanKayKitAdvKnight, KayKitAdvKnightFab);
        this.fabClasses.set(Char.CharHumanKayKitAdvMage, KayKitAdvMageFab);
        this.fabClasses.set(Char.CharHumanKayKitAdvRogue, KayKitAdvRogueFab);
        this.fabClasses.set(Char.CharHumanKayKitAdvRogueHooded, KayKitAdvRogueHoodedFab);

        this.fabClasses.set(Char.KayKitAdvArrow, KayKitArrowFab);
        this.fabClasses.set(Char.KayKitAdvArrowBundle, KayKitArrowBundleFab);
        this.fabClasses.set(Char.KayKitAdvAxe1Handed, KayKitAxe1HandedFab);
        this.fabClasses.set(Char.KayKitAdvAxe2Handed, KayKitAxe2HandedFab);
        this.fabClasses.set(Char.KayKitAdvCrossbow1Handed, KayKitCrossbow1HandedFab);
        this.fabClasses.set(Char.KayKitAdvCrossbow2Handed, KayKitCrossbow2HandedFab);
        this.fabClasses.set(Char.KayKitAdvDagger, KayKitDaggerFab);
        this.fabClasses.set(Char.KayKitAdvMugEmpty, KayKitMugEmptyFab);
        this.fabClasses.set(Char.KayKitAdvMugFull, KayKitMugFullFab);
        this.fabClasses.set(Char.KayKitAdvQuiver, KayKitQuiverFab);
        this.fabClasses.set(Char.KayKitAdvShieldBadge, KayKitShieldBadgeFab);
        this.fabClasses.set(Char.KayKitAdvShieldBadgeColor, KayKitShieldBadgeColorFab);
        this.fabClasses.set(Char.KayKitAdvShieldRound, KayKitShieldRoundFab);
        this.fabClasses.set(Char.KayKitAdvShieldRoundBarbarian, KayKitShieldRoundBarbarianFab);
        this.fabClasses.set(Char.KayKitAdvShieldRoundColor, KayKitShieldRoundColorFab);
        this.fabClasses.set(Char.KayKitAdvShieldSpikes, KayKitShieldSpikesFab);
        this.fabClasses.set(Char.KayKitAdvShieldSpikesColor, KayKitShieldSpikesColorFab);
        this.fabClasses.set(Char.KayKitAdvShieldSquare, KayKitShieldSquareFab);
        this.fabClasses.set(Char.KayKitAdvShieldSquareColor, KayKitShieldSquareColorFab);
        this.fabClasses.set(Char.KayKitAdvSmokeBomb, KayKitSmokeBombFab);
        this.fabClasses.set(Char.KayKitAdvSpellbookClosed, KayKitSpellbookClosedFab);
        this.fabClasses.set(Char.KayKitAdvSpellbookOpen, KayKitSpellbookOpenFab);
        this.fabClasses.set(Char.KayKitAdvStaff, KayKitStaffFab);
        this.fabClasses.set(Char.KayKitAdvSword1Handed, KayKitSword1HandedFab);
        this.fabClasses.set(Char.KayKitAdvSword2Handed, KayKitSword2HandedFab);
        this.fabClasses.set(Char.KayKitAdvSword2HandedColor, KayKitSword2HandedColorFab);
        this.fabClasses.set(Char.KayKitAdvWand, KayKitWandFab);

        this.fabClasses.set(Char.OceanStarterSubMarine, OceanStarterSubmarineFab);
        this.fabClasses.set(Char.OceanStarterSmallCoral, OceanStarterSmallCoralFab);
        this.fabClasses.set(Char.OceanStarterSmallBoat, OceanStarterSmallBoatFab);
        this.fabClasses.set(Char.OceanStarterPirateShip, OceanStarterPirateShipFab);
        this.fabClasses.set(Char.OceanStarterLongPlant, OceanStarterLongPlantFab);
        this.fabClasses.set(Char.OceanStarterCrashedShip, OceanStarterCrashedShipFab);
        this.fabClasses.set(Char.OceanStarterChestOld, OceanStarterChestOldFab);
        this.fabClasses.set(Char.OceanStarterChest, OceanStarterChestFab);
        this.fabClasses.set(Char.OceanStarterAnemonie, OceanStarterAnemonieFab);

        this.fabClasses.set(Char.CharAniOceanDolphin, OceanDolphinFab);
        this.fabClasses.set(Char.CharAniOceanFish1, OceanFish1Fab);
        this.fabClasses.set(Char.CharAniOceanFish2, OceanFish2Fab);
        this.fabClasses.set(Char.CharAniOceanFish3, OceanFish3Fab);
        this.fabClasses.set(Char.CharAniOceanMantaRay, OceanMantaRayFab);
        this.fabClasses.set(Char.CharAniOceanShark, OceanSharkFab);
        this.fabClasses.set(Char.CharAniOceanWhale, OceanWhaleFab);

        this.fabClasses.set(Char.CharAniEasypackFrog, EasypackFrogFab);
        this.fabClasses.set(Char.CharAniEasypackRat, EasypackRatFab);
        this.fabClasses.set(Char.CharAniEasypackSnake, EasypackSnakeFab);
        this.fabClasses.set(Char.CharAniEasypackSnakeAngry, EasypackSnakeAngryFab);
        this.fabClasses.set(Char.CharAniEasypackSpider, EasypackSpiderFab);
        this.fabClasses.set(Char.CharAniEasypackWasp, EasypackWaspFab);
        this.fabClasses.set(Char.CharMonEasypackSlime, EasypackSlimeFab);


        this.fabClasses.set(Char.CharHumanUltimate, UltimateCharFab);
        this.fabClasses.set(Char.CharHumanUltimateGun, UltimateCharGunFab);
        this.fabClasses.set(Char.UltimateCubeBricks, UltimateCubeBricksFab);
        this.fabClasses.set(Char.UltimateCubeCrate, UltimateCubeCrateFab);
        this.fabClasses.set(Char.UltimateCubeDefault, UltimateCubeDefaultFab);
        this.fabClasses.set(Char.UltimateCubeDirtSingle, UltimateCubeDirtSingleFab);
        this.fabClasses.set(Char.UltimateCubeExclamation, UltimateCubeExclamationFab);
        this.fabClasses.set(Char.UltimateCubeGrassSingle, UltimateCubeGrassSingleFab);
        this.fabClasses.set(Char.UltimateCubeQuestion, UltimateCubeQuestionFab);
        this.fabClasses.set(Char.CharMonUltimateEnermyBee, UltimateEnermyBeeFab);
        this.fabClasses.set(Char.CharMonUltimateEnermyCrab, UltimateEnermyCrabFab);
        this.fabClasses.set(Char.CharMonUltimateEnermy, UltimateEnermyFab);
        this.fabClasses.set(Char.CharMonUltimateEnermySkull, UltimateEnermySkullFab);
        this.fabClasses.set(Char.UltimateLvAndMaArrow, UltimateLvAndMaArrowFab);
        this.fabClasses.set(Char.UltimateLvAndMaArrowSide, UltimateLvAndMaArrowSideFab);
        this.fabClasses.set(Char.UltimateLvAndMaArrowUp, UltimateLvAndMaArrowUpFab);
        this.fabClasses.set(Char.UltimateLvAndMaBomb, UltimateLvAndMaBombFab);
        this.fabClasses.set(Char.UltimateLvAndMaBouncer, UltimateLvAndMaBouncerFab);
        this.fabClasses.set(Char.UltimateLvAndMaBridgeModular, UltimateLvAndMaBridgeModularFab);
        this.fabClasses.set(Char.UltimateLvAndMaBridgeModularCenter, UltimateLvAndMaBridgeModularCenterFab);
        this.fabClasses.set(Char.UltimateLvAndMaBridgeSmall, UltimateLvAndMaBridgeSmallFab);
        this.fabClasses.set(Char.UltimateLvAndMaCannon, UltimateLvAndMaCannonFab);
        this.fabClasses.set(Char.UltimateLvAndMaCannonBall, UltimateLvAndMaCannonBallFab);
        this.fabClasses.set(Char.UltimateLvAndMaChest, UltimateLvAndMaChestFab);
        this.fabClasses.set(Char.UltimateLvAndMaDoor, UltimateLvAndMaDoorFab);
        this.fabClasses.set(Char.UltimateLvAndMaFence1, UltimateLvAndMaFence1Fab);
        this.fabClasses.set(Char.UltimateLvAndMaFenceCorner, UltimateLvAndMaFenceCornerFab);
        this.fabClasses.set(Char.UltimateLvAndMaFenceMiddle, UltimateLvAndMaFenceMiddleFab);
        this.fabClasses.set(Char.UltimateLvAndMaGoalFlag, UltimateLvAndMaGoalFlagFab);
        this.fabClasses.set(Char.UltimateLvAndMaHazardCylinder, UltimateLvAndMaHazardCylinderFab);
        this.fabClasses.set(Char.UltimateLvAndMaHazardSaw, UltimateLvAndMaHazardSawFab);
        this.fabClasses.set(Char.UltimateLvAndMaHazardSpikeTrap, UltimateLvAndMaHazardSpikeTrapFab);
        this.fabClasses.set(Char.UltimateLvAndMaLever, UltimateLvAndMaLeverFab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers0, UltimateLvAndMaNumber0Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers1, UltimateLvAndMaNumber1Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers2, UltimateLvAndMaNumber2Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers3, UltimateLvAndMaNumber3Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers4, UltimateLvAndMaNumber4Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers5, UltimateLvAndMaNumber5Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers6, UltimateLvAndMaNumber6Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers7, UltimateLvAndMaNumber7Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers8, UltimateLvAndMaNumber8Fab);
        this.fabClasses.set(Char.UltimateLvAndMaNumbers9, UltimateLvAndMaNumber9Fab);
        this.fabClasses.set(Char.UltimateLvAndMaPipe90, UltimateLvAndMaPipe90Fab);
        this.fabClasses.set(Char.UltimateLvAndMaPipeEnd, UltimateLvAndMaPipeEndFab);
        this.fabClasses.set(Char.UltimateLvAndMaPipeStraight, UltimateLvAndMaPipeStraightFab);
        this.fabClasses.set(Char.UltimateLvAndMaPipeT, UltimateLvAndMaPipeTFab);
        this.fabClasses.set(Char.UltimateLvAndMaPlantLarge, UltimateLvAndMaPlantLargeFab);
        this.fabClasses.set(Char.UltimateLvAndMaPlantSmall, UltimateLvAndMaPlantSmallFab);
        this.fabClasses.set(Char.UltimateLvAndMaSpikes, UltimateLvAndMaSpikesFab);
        this.fabClasses.set(Char.UltimateLvAndMaSpikyBall, UltimateLvAndMaSpikyBallFab);
        this.fabClasses.set(Char.UltimateLvAndMaStairs, UltimateLvAndMaStairsFab);
        this.fabClasses.set(Char.UltimateLvAndMaStairsModularEnd, UltimateLvAndMaStairsModularEndFab);
        this.fabClasses.set(Char.UltimateLvAndMaStairsModularMiddle, UltimateLvAndMaStairsModularMiddleFab);
        this.fabClasses.set(Char.UltimateLvAndMaStairsModularStart, UltimateLvAndMaStairsModularStartFab);
        this.fabClasses.set(Char.UltimateLvAndMaStairsSmall, UltimateLvAndMaStairsSmallFab);
        this.fabClasses.set(Char.UltimateLvAndMaTower, UltimateLvAndMaTowerFab);
        this.fabClasses.set(Char.UltimateModPlatform2DCubeDirt1x1Center, UltimateModPlatform2DCubeDirt1x1CenterFab);
        this.fabClasses.set(Char.UltimateModPlatform2DCubeDirt1x1End, UltimateModPlatform2DCubeDirt1x1EndFab);
        this.fabClasses.set(Char.UltimateModPlatform2DCubeGrass1x1Center, UltimateModPlatform2DCubeGrass1x1CenterFab);
        this.fabClasses.set(Char.UltimateModPlatform2DCubeGrass1x1End, UltimateModPlatform2DCubeGrass1x1EndFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeDirtCenterTall, UltimateModPlatform3DCubeDirtCenterTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeDirtCornerTall, UltimateModPlatform3DCubeDirtCornerTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeDirtSideTall, UltimateModPlatform3DCubeDirtSideTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassBottomTall, UltimateModPlatform3DCubeGrassBottomTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassCornerBottomTall, UltimateModPlatform3DCubeGrassCornerBottomTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassCornerCenterTall, UltimateModPlatform3DCubeGrassCornerCenterTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassCornerTall, UltimateModPlatform3DCubeGrassCornerTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassSideBottomTall, UltimateModPlatform3DCubeGrassSideBottomTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassSideCenterTall, UltimateModPlatform3DCubeGrassSideCenterTallFab);
        this.fabClasses.set(Char.UltimateModPlatform3DCubeGrassSideTall, UltimateModPlatform3DCubeGrassSideTallFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleCubeDirt, UltimateModPlatformSingleCubeDirtFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleCubeGrass, UltimateModPlatformSingleCubeGrassFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightDirtCenter, UltimateModPlatformSingleHeightDirtCenterFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightDirtCorner, UltimateModPlatformSingleHeightDirtCornerFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightDirtSide, UltimateModPlatformSingleHeightDirtSideFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightGrassCenter, UltimateModPlatformSingleHeightGrassCenterFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightGrassCorner, UltimateModPlatformSingleHeightGrassCornerFab);
        this.fabClasses.set(Char.UltimateModPlatformSingleHeightGrassSide, UltimateModPlatformSingleHeightGrassSideFab);
        this.fabClasses.set(Char.UltimateNatureBush, UltimateNatureBushFab);
        this.fabClasses.set(Char.UltimateNatureBushFruit, UltimateNatureBushFruitFab);
        this.fabClasses.set(Char.UltimateNatureCloud1, UltimateNatureCloud1Fab);
        this.fabClasses.set(Char.UltimateNatureCloud2, UltimateNatureCloud2Fab);
        this.fabClasses.set(Char.UltimateNatureCloud3, UltimateNatureCloud3Fab);
        this.fabClasses.set(Char.UltimateNatureFruit, UltimateNatureFruitFab);
        this.fabClasses.set(Char.UltimateNatureGrass1, UltimateNatureGrass1Fab);
        this.fabClasses.set(Char.UltimateNatureGrass2, UltimateNatureGrass2Fab);
        this.fabClasses.set(Char.UltimateNatureGrass3, UltimateNatureGrass3Fab);
        this.fabClasses.set(Char.UltimateNatureRock1, UltimateNatureRock1Fab);
        this.fabClasses.set(Char.UltimateNatureRock2, UltimateNatureRock2Fab);
        this.fabClasses.set(Char.UltimateNatureRockPlatformTall, UltimateNatureRockPlatformTallFab);
        this.fabClasses.set(Char.UltimateNatureRockPlatforms1, UltimateNatureRockPlatforms1Fab);
        this.fabClasses.set(Char.UltimateNatureRockPlatforms2, UltimateNatureRockPlatforms2Fab);
        this.fabClasses.set(Char.UltimateNatureRockPlatforms3, UltimateNatureRockPlatforms3Fab);
        this.fabClasses.set(Char.UltimateNatureRockPlatformsLarge, UltimateNatureRockPlatformsLargeFab);
        this.fabClasses.set(Char.UltimateNatureRockPlatformsMedium, UltimateNatureRockPlatformsMediumFab);
        this.fabClasses.set(Char.UltimateNatureTree, UltimateNatureTreeFab);
        this.fabClasses.set(Char.UltimateNatureTreeFruit, UltimateNatureTreeFruitFab);
        this.fabClasses.set(Char.UltimatePAPCoin, UltimatePAPCoinFab);
        this.fabClasses.set(Char.UltimatePAPGemBlue, UltimatePAPGemBlueFab);
        this.fabClasses.set(Char.UltimatePAPGemGreen, UltimatePAPGemGreenFab);
        this.fabClasses.set(Char.UltimatePAPGemPink, UltimatePAPGemPinkFab);
        this.fabClasses.set(Char.UltimatePAPHeart, UltimatePAPHeartFab);
        this.fabClasses.set(Char.UltimatePAPHeartHalf, UltimatePAPHeartHalfFab);
        this.fabClasses.set(Char.UltimatePAPHeartOutline, UltimatePAPHeartOutlineFab);
        this.fabClasses.set(Char.UltimatePAPKey, UltimatePAPKeyFab);
        this.fabClasses.set(Char.UltimatePAPStar, UltimatePAPStarFab);
        this.fabClasses.set(Char.UltimatePAPStarOutline, UltimatePAPStarOutlineFab);
        this.fabClasses.set(Char.UltimatePAPThunder, UltimatePAPThunderFab);

        // Pet
        this.fabClasses.set(Char.CharAniBilby, BilbyFab);
        this.fabClasses.set(Char.CharAniDog, DogFab);
        this.fabClasses.set(Char.CharAniCat, CatFab);
        this.fabClasses.set(Char.CharAniBee, BeeFab);
        this.fabClasses.set(Char.CharAniPetSnake, PetSnakeFab);

        // Farm Pet
        this.fabClasses.set(Char.CharAniFarmPetCow, FarmPetCowFab);
        this.fabClasses.set(Char.CharAniFarmPetHorse, FarmPetHorseFab);
        this.fabClasses.set(Char.CharAniFarmPetLlama, FarmPetLlamaFab);
        this.fabClasses.set(Char.CharAniFarmPetPig, FarmPetPigFab);
        this.fabClasses.set(Char.CharAniFarmPetPug, FarmPetPugFab);
        this.fabClasses.set(Char.CharAniFarmPetSheep, FarmPetSheepFab);
        this.fabClasses.set(Char.CharAniFarmPetZebra, FarmPetZebraFab);

        // Stup
        this.fabClasses.set(Char.Bat, BatFab);
        this.fabClasses.set(Char.Gun, GunFab);
        this.fabClasses.set(Char.Stone, StoneFab);
        this.fabClasses.set(Char.Bed, BedFab);
        this.fabClasses.set(Char.Bath, BathFab);
        this.fabClasses.set(Char.Bookshelf, BookShelfFab);
        this.fabClasses.set(Char.Closet, ClosetFab);
        this.fabClasses.set(Char.Desk, DeskFab);
        this.fabClasses.set(Char.Kitchen, KitchenFab);
        this.fabClasses.set(Char.KitTable, KitTableFab);
        this.fabClasses.set(Char.Oven, OvenFab);
        this.fabClasses.set(Char.Refrigerator, RefrigeratorFab);
        this.fabClasses.set(Char.Sink, SinkFab);
        this.fabClasses.set(Char.Table, TableFab);
        this.fabClasses.set(Char.Toilet, ToiletFab);
        this.fabClasses.set(Char.TV, TvFab);

        this.fabClasses.set(Char.FluffyTree, FluffyTreeFab);
        this.fabClasses.set(Char.AppleTree, AppleTreeFab);
        this.fabClasses.set(Char.Apple, AppleFab);
        this.fabClasses.set(Char.CoconutTree, CoconutTreeFab);
        this.fabClasses.set(Char.Coconut, CoconutFab);
        this.fabClasses.set(Char.DeadTree2, DeadTree2Fab);
        this.fabClasses.set(Char.Tomato0, Tomato0Fab);
        this.fabClasses.set(Char.Tomato1, Tomato1Fab);
        this.fabClasses.set(Char.Tomato2, Tomato2Fab);
        this.fabClasses.set(Char.Potato0, Potato0Fab);
        this.fabClasses.set(Char.Potato1, Potato1Fab);
        this.fabClasses.set(Char.Potato2, Potato2Fab);
        this.fabClasses.set(Char.Carrot0, Carrot0Fab);
        this.fabClasses.set(Char.Carrot1, Carrot1Fab);
        this.fabClasses.set(Char.Carrot2, Carrot2Fab);

        this.fabClasses.set(Char.Grass, GrassFab);

        this.fabClasses.set(Char.WateringCan, WarteringCanFab);
        this.fabClasses.set(Char.Hammer, HammerFab);

        this.fabClasses.set(Char.Empty, EmptyFab);


        // 추가 모델은 여기서 계속 등록
        this.fabClasses.set(Char.KayKitDungeoncrossbowrare, KayKitDungeoncrossbowrareFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallmediumcornerRight, KayKitDungeonscaffoldsmallmediumcornerRightFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldlowcornerRight, KayKitDungeonscaffoldlowcornerRightFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallmediumlong, KayKitDungeonscaffoldsmallmediumlongFab);
        this.fabClasses.set(Char.KayKitDungeoncrateDark, KayKitDungeoncrateDarkFab);
        this.fabClasses.set(Char.KayKitDungeonaxeDoubleuncommon, KayKitDungeonaxeDoubleuncommonFab);
        this.fabClasses.set(Char.KayKitDungeonfloorDecorationwoodLeft, KayKitDungeonfloorDecorationwoodLeftFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallmediumcornerLeft, KayKitDungeonscaffoldsmallmediumcornerLeftFab);
        this.fabClasses.set(Char.KayKitDungeonlootSackA, KayKitDungeonlootSackAFab);
        this.fabClasses.set(Char.KayKitDungeonbookcasebroken, KayKitDungeonbookcasebrokenFab);
        this.fabClasses.set(Char.KayKitDungeonplateFull, KayKitDungeonplateFullFab);
        this.fabClasses.set(Char.KayKitDungeoncoinsLarge, KayKitDungeoncoinsLargeFab);
        this.fabClasses.set(Char.KayKitDungeonpotionMediumgreen, KayKitDungeonpotionMediumgreenFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmalllowcornerLeft, KayKitDungeonscaffoldsmalllowcornerLeftFab);
        this.fabClasses.set(Char.KayKitDungeonbookcaseFilled, KayKitDungeonbookcaseFilledFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldhighrailing, KayKitDungeonscaffoldhighrailingFab);
        this.fabClasses.set(Char.KayKitDungeonwallbroken, KayKitDungeonwallbrokenFab);
        this.fabClasses.set(Char.KayKitDungeonchestuncommon, KayKitDungeonchestuncommonFab);
        this.fabClasses.set(Char.KayKitDungeonpotionMediumred, KayKitDungeonpotionMediumredFab);
        this.fabClasses.set(Char.KayKitDungeonwallDecorationA, KayKitDungeonwallDecorationAFab);
        this.fabClasses.set(Char.KayKitDungeonpotB, KayKitDungeonpotBFab);
        this.fabClasses.set(Char.KayKitDungeonwallgateDoor, KayKitDungeonwallgateDoorFab);
        this.fabClasses.set(Char.KayKitDungeonhammeruncommon, KayKitDungeonhammeruncommonFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldmediumrailing, KayKitDungeonscaffoldmediumrailingFab);
        this.fabClasses.set(Char.KayKitDungeonwallgate, KayKitDungeonwallgateFab);
        this.fabClasses.set(Char.KayKitDungeonwalldoor, KayKitDungeonwalldoorFab);
        this.fabClasses.set(Char.KayKitDungeonpotionLargeblue, KayKitDungeonpotionLargeblueFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldlowcornerBoth, KayKitDungeonscaffoldlowcornerBothFab);
        this.fabClasses.set(Char.KayKitDungeonbookcaseWidebroken, KayKitDungeonbookcaseWidebrokenFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallhighcornerLeft, KayKitDungeonscaffoldsmallhighcornerLeftFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldmediumcornerLeft, KayKitDungeonscaffoldmediumcornerLeftFab);
        this.fabClasses.set(Char.KayKitDungeonfloorDecorationwoodRight, KayKitDungeonfloorDecorationwoodRightFab);
        this.fabClasses.set(Char.KayKitDungeontorch, KayKitDungeontorchFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallhigh, KayKitDungeonscaffoldsmallhighFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldmediumcornerBoth, KayKitDungeonscaffoldmediumcornerBothFab);
        this.fabClasses.set(Char.KayKitDungeonchestcommonempty, KayKitDungeonchestcommonemptyFab);
        this.fabClasses.set(Char.KayKitDungeonbookA, KayKitDungeonbookAFab);
        this.fabClasses.set(Char.KayKitDungeonbookF, KayKitDungeonbookFFab);
        this.fabClasses.set(Char.KayKitDungeonartifact, KayKitDungeonartifactFab);
        this.fabClasses.set(Char.KayKitDungeontorchWall, KayKitDungeontorchWallFab);
        this.fabClasses.set(Char.KayKitDungeonwallSingle, KayKitDungeonwallSingleFab);
        this.fabClasses.set(Char.KayKitDungeonwallSinglewindow, KayKitDungeonwallSinglewindowFab);
        this.fabClasses.set(Char.KayKitDungeonaxeuncommon, KayKitDungeonaxeuncommonFab);
        this.fabClasses.set(Char.KayKitDungeonbarrel, KayKitDungeonbarrelFab);
        this.fabClasses.set(Char.KayKitDungeonpotionMediumblue, KayKitDungeonpotionMediumblueFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallhighrailinglong, KayKitDungeonscaffoldsmallhighrailinglongFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldmedium, KayKitDungeonscaffoldmediumFab);
        this.fabClasses.set(Char.KayKitDungeoncratePlatformmedium, KayKitDungeoncratePlatformmediumFab);
        this.fabClasses.set(Char.KayKitDungeonwallSingledecorationB, KayKitDungeonwallSingledecorationBFab);
        this.fabClasses.set(Char.KayKitDungeonaxecommon, KayKitDungeonaxecommonFab);
        this.fabClasses.set(Char.KayKitDungeonpotCdecorated, KayKitDungeonpotCdecoratedFab);
        this.fabClasses.set(Char.KayKitDungeonbookE, KayKitDungeonbookEFab);
        this.fabClasses.set(Char.KayKitDungeondoor, KayKitDungeondoorFab);
        this.fabClasses.set(Char.KayKitDungeondoorgate, KayKitDungeondoorgateFab);
        this.fabClasses.set(Char.KayKitDungeonwallSinglecorner, KayKitDungeonwallSinglecornerFab);
        this.fabClasses.set(Char.KayKitDungeonpotionLargered, KayKitDungeonpotionLargeredFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallhighcornerRight, KayKitDungeonscaffoldsmallhighcornerRightFab);
        this.fabClasses.set(Char.KayKitDungeonwallSinglesplit, KayKitDungeonwallSinglesplitFab);
        this.fabClasses.set(Char.KayKitDungeonchestraremimic, KayKitDungeonchestraremimicFab);
        this.fabClasses.set(Char.KayKitDungeoncrate, KayKitDungeoncrateFab);
        this.fabClasses.set(Char.KayKitDungeonbucket, KayKitDungeonbucketFab);
        this.fabClasses.set(Char.KayKitDungeonaxerare, KayKitDungeonaxerareFab);
        this.fabClasses.set(Char.KayKitDungeonstaffuncommon, KayKitDungeonstaffuncommonFab);
        this.fabClasses.set(Char.KayKitDungeonshieldcommon, KayKitDungeonshieldcommonFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldhighcornerBoth, KayKitDungeonscaffoldhighcornerBothFab);
        this.fabClasses.set(Char.KayKitDungeonpotionLargegreen, KayKitDungeonpotionLargegreenFab);
        this.fabClasses.set(Char.KayKitDungeonbookC, KayKitDungeonbookCFab);
        this.fabClasses.set(Char.KayKitDungeonwallSinglebroken, KayKitDungeonwallSinglebrokenFab);
        this.fabClasses.set(Char.KayKitDungeonfloorDecorationtilesLarge, KayKitDungeonfloorDecorationtilesLargeFab);
        this.fabClasses.set(Char.KayKitDungeonbookcaseWide, KayKitDungeonbookcaseWideFab);
        this.fabClasses.set(Char.KayKitDungeonpotionSmallgreen, KayKitDungeonpotionSmallgreenFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldhigh, KayKitDungeonscaffoldhighFab);
        this.fabClasses.set(Char.KayKitDungeonhammercommon, KayKitDungeonhammercommonFab);
        this.fabClasses.set(Char.KayKitDungeonwallendbroken, KayKitDungeonwallendbrokenFab);
        this.fabClasses.set(Char.KayKitDungeonwallSingledecorationA, KayKitDungeonwallSingledecorationAFab);
        this.fabClasses.set(Char.KayKitDungeonquiverempty, KayKitDungeonquiveremptyFab);
        this.fabClasses.set(Char.KayKitDungeonbookD, KayKitDungeonbookDFab);
        this.fabClasses.set(Char.KayKitDungeonpillar, KayKitDungeonpillarFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldhighcornerRight, KayKitDungeonscaffoldhighcornerRightFab);
        this.fabClasses.set(Char.KayKitDungeonweaponRack, KayKitDungeonweaponRackFab);
        this.fabClasses.set(Char.KayKitDungeonbookOpenB, KayKitDungeonbookOpenBFab);
        this.fabClasses.set(Char.KayKitDungeontableSmall, KayKitDungeontableSmallFab);
        this.fabClasses.set(Char.KayKitDungeonaxeDoublecommon, KayKitDungeonaxeDoublecommonFab);
        this.fabClasses.set(Char.KayKitDungeonbarrelDark, KayKitDungeonbarrelDarkFab);
        this.fabClasses.set(Char.KayKitDungeonwallCorner, KayKitDungeonwallCornerFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmalllowrailing, KayKitDungeonscaffoldsmalllowrailingFab);
        this.fabClasses.set(Char.KayKitDungeonswordcommon, KayKitDungeonswordcommonFab);
        this.fabClasses.set(Char.KayKitDungeonaxeDoublerare, KayKitDungeonaxeDoublerareFab);
        this.fabClasses.set(Char.KayKitDungeonpots, KayKitDungeonpotsFab);
        this.fabClasses.set(Char.KayKitDungeonfloorDecorationshatteredBricks, KayKitDungeonfloorDecorationshatteredBricksFab);
        this.fabClasses.set(Char.KayKitDungeonquiverfull, KayKitDungeonquiverfullFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallhighrailing, KayKitDungeonscaffoldsmallhighrailingFab);
        this.fabClasses.set(Char.KayKitDungeonstaffcommon, KayKitDungeonstaffcommonFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmalllow, KayKitDungeonscaffoldsmalllowFab);
        this.fabClasses.set(Char.KayKitDungeontableLarge, KayKitDungeontableLargeFab);
        this.fabClasses.set(Char.KayKitDungeonchestTopraremimic, KayKitDungeonchestTopraremimicFab);
        this.fabClasses.set(Char.KayKitDungeoncratePlatformsmall, KayKitDungeoncratePlatformsmallFab);
        this.fabClasses.set(Char.KayKitDungeoncrossbowcommon, KayKitDungeoncrossbowcommonFab);
        this.fabClasses.set(Char.KayKitDungeontileBrickBsmall, KayKitDungeontileBrickBsmallFab);
        this.fabClasses.set(Char.KayKitDungeonwallSingledoor, KayKitDungeonwallSingledoorFab);
        this.fabClasses.set(Char.KayKitDungeonpillarbroken, KayKitDungeonpillarbrokenFab);
        this.fabClasses.set(Char.KayKitDungeonshieldrare, KayKitDungeonshieldrareFab);
        this.fabClasses.set(Char.KayKitDungeonbookcase, KayKitDungeonbookcaseFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallmediumrailinglong, KayKitDungeonscaffoldsmallmediumrailinglongFab);
        this.fabClasses.set(Char.KayKitDungeonwallgateCorner, KayKitDungeonwallgateCornerFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldhighcornerLeft, KayKitDungeonscaffoldhighcornerLeftFab);
        this.fabClasses.set(Char.KayKitDungeonstairswide, KayKitDungeonstairswideFab);
        this.fabClasses.set(Char.KayKitDungeonbanner, KayKitDungeonbannerFab);
        this.fabClasses.set(Char.KayKitDungeonstairs, KayKitDungeonstairsFab);
        this.fabClasses.set(Char.KayKitDungeontileBrickBmedium, KayKitDungeontileBrickBmediumFab);
        this.fabClasses.set(Char.KayKitDungeoncoinsSmall, KayKitDungeoncoinsSmallFab);
        this.fabClasses.set(Char.KayKitDungeonshielduncommon, KayKitDungeonshielduncommonFab);
        this.fabClasses.set(Char.KayKitDungeontileSpikeslarge, KayKitDungeontileSpikeslargeFab);
        this.fabClasses.set(Char.KayKitDungeonbench, KayKitDungeonbenchFab);
        this.fabClasses.set(Char.KayKitDungeonchestuncommonmimic, KayKitDungeonchestuncommonmimicFab);
        this.fabClasses.set(Char.KayKitDungeonstaffrare, KayKitDungeonstaffrareFab);
        this.fabClasses.set(Char.KayKitDungeonchestTopcommonempty, KayKitDungeonchestTopcommonemptyFab);
        this.fabClasses.set(Char.KayKitDungeonbookOpenA, KayKitDungeonbookOpenAFab);
        this.fabClasses.set(Char.KayKitDungeonhammerrare, KayKitDungeonhammerrareFab);
        this.fabClasses.set(Char.KayKitDungeonpotAdecorated, KayKitDungeonpotAdecoratedFab);
        this.fabClasses.set(Char.KayKitDungeonbricks, KayKitDungeonbricksFab);
        this.fabClasses.set(Char.KayKitDungeonbookB, KayKitDungeonbookBFab);
        this.fabClasses.set(Char.KayKitDungeonspellBook, KayKitDungeonspellBookFab);
        this.fabClasses.set(Char.KayKitDungeontileBrickBlargeCrackedB, KayKitDungeontileBrickBlargeCrackedBFab);
        this.fabClasses.set(Char.KayKitDungeonchestcommon, KayKitDungeonchestcommonFab);
        this.fabClasses.set(Char.KayKitDungeonbookcaseWideFilledbroken, KayKitDungeonbookcaseWideFilledbrokenFab);
        this.fabClasses.set(Char.KayKitDungeonlootSackB, KayKitDungeonlootSackBFab);
        this.fabClasses.set(Char.KayKitDungeonfloorDecorationwood, KayKitDungeonfloorDecorationwoodFab);
        this.fabClasses.set(Char.KayKitDungeonmug, KayKitDungeonmugFab);
        this.fabClasses.set(Char.KayKitDungeontileBrickAmedium, KayKitDungeontileBrickAmediumFab);
        this.fabClasses.set(Char.KayKitDungeonpotC, KayKitDungeonpotCFab);
        this.fabClasses.set(Char.KayKitDungeondaggercommon, KayKitDungeondaggercommonFab);
        this.fabClasses.set(Char.KayKitDungeonchestrare, KayKitDungeonchestrareFab);
        this.fabClasses.set(Char.KayKitDungeondaggerrare, KayKitDungeondaggerrareFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallmediumrailing, KayKitDungeonscaffoldsmallmediumrailingFab);
        this.fabClasses.set(Char.KayKitDungeonplate, KayKitDungeonplateFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldmediumcornerRight, KayKitDungeonscaffoldmediumcornerRightFab);
        this.fabClasses.set(Char.KayKitDungeonstool, KayKitDungeonstoolFab);
        this.fabClasses.set(Char.KayKitDungeonswordrare, KayKitDungeonswordrareFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldstairs, KayKitDungeonscaffoldstairsFab);
        this.fabClasses.set(Char.KayKitDungeontileBrickBlargeCrackedA, KayKitDungeontileBrickBlargeCrackedAFab);
        this.fabClasses.set(Char.KayKitDungeonchestTopuncommon, KayKitDungeonchestTopuncommonFab);
        this.fabClasses.set(Char.KayKitDungeontileBrickAlarge, KayKitDungeontileBrickAlargeFab);
        this.fabClasses.set(Char.KayKitDungeonwallIntersection, KayKitDungeonwallIntersectionFab);
        this.fabClasses.set(Char.KayKitDungeonpotionSmallblue, KayKitDungeonpotionSmallblueFab);
        this.fabClasses.set(Char.KayKitDungeonwall, KayKitDungeonwallFab);
        this.fabClasses.set(Char.KayKitDungeonwallSplit, KayKitDungeonwallSplitFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallmedium, KayKitDungeonscaffoldsmallmediumFab);
        this.fabClasses.set(Char.KayKitDungeonplateHalf, KayKitDungeonplateHalfFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmalllowlong, KayKitDungeonscaffoldsmalllowlongFab);
        this.fabClasses.set(Char.KayKitDungeonfloorDecorationtilesSmall, KayKitDungeonfloorDecorationtilesSmallFab);
        this.fabClasses.set(Char.KayKitDungeonpotionSmallred, KayKitDungeonpotionSmallredFab);
        this.fabClasses.set(Char.KayKitDungeonwallSinglewindowGate, KayKitDungeonwallSinglewindowGateFab);
        this.fabClasses.set(Char.KayKitDungeontileSpikesshallow, KayKitDungeontileSpikesshallowFab);
        this.fabClasses.set(Char.KayKitDungeonwallDecorationB, KayKitDungeonwallDecorationBFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldlowrailing, KayKitDungeonscaffoldlowrailingFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldlow, KayKitDungeonscaffoldlowFab);
        this.fabClasses.set(Char.KayKitDungeoncratePlatformlarge, KayKitDungeoncratePlatformlargeFab);
        this.fabClasses.set(Char.KayKitDungeonwallwindow, KayKitDungeonwallwindowFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmalllowrailinglong, KayKitDungeonscaffoldsmalllowrailinglongFab);
        this.fabClasses.set(Char.KayKitDungeoncoin, KayKitDungeoncoinFab);
        this.fabClasses.set(Char.KayKitDungeonchestTopuncommonmimic, KayKitDungeonchestTopuncommonmimicFab);
        this.fabClasses.set(Char.KayKitDungeonpotA, KayKitDungeonpotAFab);
        this.fabClasses.set(Char.KayKitDungeontileBrickBlarge, KayKitDungeontileBrickBlargeFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmalllowcornerRight, KayKitDungeonscaffoldsmalllowcornerRightFab);
        this.fabClasses.set(Char.KayKitDungeonchair, KayKitDungeonchairFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldsmallhighlong, KayKitDungeonscaffoldsmallhighlongFab);
        this.fabClasses.set(Char.KayKitDungeonarrow, KayKitDungeonarrowFab);
        this.fabClasses.set(Char.KayKitDungeonquiverhalffull, KayKitDungeonquiverhalffullFab);
        this.fabClasses.set(Char.KayKitDungeoncoinsMedium, KayKitDungeoncoinsMediumFab);
        this.fabClasses.set(Char.KayKitDungeonscaffoldlowcornerLeft, KayKitDungeonscaffoldlowcornerLeftFab);
        this.fabClasses.set(Char.KayKitDungeonbookcaseFilledbroken, KayKitDungeonbookcaseFilledbrokenFab);
        this.fabClasses.set(Char.KayKitDungeonwallend, KayKitDungeonwallendFab);
        this.fabClasses.set(Char.KayKitDungeontableMedium, KayKitDungeontableMediumFab);
        this.fabClasses.set(Char.KayKitDungeonbookcaseWideFilled, KayKitDungeonbookcaseWideFilledFab);
        this.fabClasses.set(Char.KayKitDungeoncrossbowuncommon, KayKitDungeoncrossbowuncommonFab);
        this.fabClasses.set(Char.KayKitDungeonsworduncommon, KayKitDungeonsworduncommonFab);
        this.fabClasses.set(Char.KayKitDungeonpotBdecorated, KayKitDungeonpotBdecoratedFab);
        this.fabClasses.set(Char.KayKitDungeontileBrickAsmall, KayKitDungeontileBrickAsmallFab);
        this.fabClasses.set(Char.KayKitDungeonchestToprare, KayKitDungeonchestToprareFab);
        this.fabClasses.set(Char.KayKitDungeondaggeruncommon, KayKitDungeondaggeruncommonFab);
        this.fabClasses.set(Char.KayKitDungeontileSpikes, KayKitDungeontileSpikesFab);
        this.fabClasses.set(Char.KayKitDungeonwallwindowGate, KayKitDungeonwallwindowGateFab);
        this.fabClasses.set(Char.KayKitDungeonchestTopcommon, KayKitDungeonchestTopcommonFab);
        this.fabClasses.set(Char.KayKitDungeontrapdoor, KayKitDungeontrapdoorFab);
    }

    GetAssets(id: Char): IAsset {
        if (!this.fabInstances.has(id)) {
            const FabClass = this.fabClasses.get(id);
            if (!FabClass) {
                console.warn(`Fab class for ${id} not found. Using default MaleFab.`);
                return this.GetAssets(Char.CharHumanMale);
            }
            const instance = new FabClass(this);
            this.fabInstances.set(id, instance);
        }
        return this.fabInstances.get(id)!;
    }

    get Load(): GLTFLoader {
        return this.loader;
    }

    get LoadingManager(): THREE.LoadingManager {
        return this.loadingManager;
    }

    get FBXLoader(): FBXLoader {
        return this.fbxLoader;
    }
}
