import { CurrencyType } from "@Glibs/inventory/wallet";
import { StrategicPlanetDef, StrategicRouteDef } from "./strategicgalaxytypes";
import { RivalCitySeed } from "@Glibs/gameobjects/rivalcity/rivalcitytypes";

// ─── 행성 Gameplay 정의 ───────────────────────────────────────────────────────

export const strategicPlanetDefs: Record<string, StrategicPlanetDef> = {
  atlas: {
    id: "atlas",
    name: "Atlas",
    description: "은하의 중앙 관문. 모든 주요 항로가 이곳을 통과한다.",
    defaultFactionId: "guild",
    profileId: "gateworld",
    routeIds: ["atlas-hephaestus", "atlas-athena", "atlas-eden", "atlas-hades"],
    citySlots: 3,
    resourceBias: {
      [CurrencyType.Gold]: 1.3,
      [CurrencyType.Food]: 1.1,
    },
    specialResources: ["gateInfluence"],
    baseStats: {
      economy: 88,
      industry: 62,
      defense: 70,
      population: 74,
      logistics: 95,
      marketScale: 90,
    },
  },
  hephaestus: {
    id: "hephaestus",
    name: "Hephaestus",
    description: "대규모 조선소와 수리 독이 자리한 Guild 군수 성계.",
    defaultFactionId: "guild",
    profileId: "industrial",
    routeIds: ["atlas-hephaestus", "hephaestus-selene"],
    citySlots: 2,
    resourceBias: {
      [CurrencyType.Materials]: 1.4,
      [CurrencyType.Gems]: 1.2,
    },
    specialResources: ["shipyardContract"],
    baseStats: {
      economy: 49,
      industry: 89,
      defense: 59,
      population: 41,
      logistics: 65,
      marketScale: 45,
    },
  },
  selene: {
    id: "selene",
    name: "Selene",
    description: "얼음 결정과 냉각 기술이 발달한 Hephaestus 외곽 위성권.",
    defaultFactionId: "guild",
    profileId: "ice-moon",
    routeIds: ["hephaestus-selene"],
    citySlots: 1,
    resourceBias: {
      [CurrencyType.Water]: 1.25,
      [CurrencyType.Electric]: 1.1,
    },
    specialResources: ["iceCrystal"],
    baseStats: {
      economy: 40,
      industry: 55,
      defense: 48,
      population: 32,
      logistics: 52,
      marketScale: 38,
    },
  },
  eden: {
    id: "eden",
    name: "Eden",
    description: "풍요로운 생태계를 가진 Alliance의 식량 성계.",
    defaultFactionId: "alliance",
    profileId: "biosphere",
    routeIds: ["atlas-eden", "eden-vega"],
    citySlots: 3,
    resourceBias: {
      [CurrencyType.Food]: 1.5,
      [CurrencyType.Water]: 1.3,
    },
    specialResources: ["bioCrystal"],
    baseStats: {
      economy: 65,
      industry: 42,
      defense: 55,
      population: 88,
      logistics: 60,
      marketScale: 55,
    },
  },
  sirius: {
    id: "sirius",
    name: "Sirius",
    description: "동부 외곽의 푸른 관문. Alliance 정찰대가 배치된 전초 성계.",
    defaultFactionId: "alliance",
    profileId: "frontier",
    routeIds: ["sirius-orion", "sirius-vega"],
    citySlots: 2,
    resourceBias: {
      [CurrencyType.Electric]: 1.2,
    },
    specialResources: ["helium3"],
    baseStats: {
      economy: 62,
      industry: 58,
      defense: 54,
      population: 51,
      logistics: 55,
      marketScale: 40,
    },
  },
  orion: {
    id: "orion",
    name: "Orion",
    description: "Sirius 관문 너머의 헬륨 채굴 전초 성계.",
    defaultFactionId: "neutral",
    profileId: "gas-frontier",
    routeIds: ["sirius-orion"],
    citySlots: 1,
    resourceBias: {
      [CurrencyType.Electric]: 1.25,
      [CurrencyType.Materials]: 1.05,
    },
    specialResources: ["helium3"],
    baseStats: {
      economy: 46,
      industry: 54,
      defense: 42,
      population: 29,
      logistics: 47,
      marketScale: 34,
    },
  },
  vega: {
    id: "vega",
    name: "Vega",
    description: "Alliance의 상업 회랑 핵심. 동부 경제권의 물류가 이곳을 통과한다.",
    defaultFactionId: "alliance",
    profileId: "trade",
    routeIds: ["sirius-vega", "vega-athena", "eden-vega"],
    citySlots: 3,
    resourceBias: {
      [CurrencyType.Gold]: 1.2,
      [CurrencyType.Materials]: 1.1,
    },
    specialResources: ["rareEarth"],
    baseStats: {
      economy: 74,
      industry: 66,
      defense: 61,
      population: 65,
      logistics: 72,
      marketScale: 70,
    },
  },
  athena: {
    id: "athena",
    name: "Athena",
    description: "Atlas와 Vega를 잇는 연구·특허 교역 허브.",
    defaultFactionId: "guild",
    profileId: "research-hub",
    routeIds: ["atlas-athena", "vega-athena"],
    citySlots: 2,
    resourceBias: {
      [CurrencyType.Gold]: 1.15,
      [CurrencyType.Electric]: 1.15,
    },
    specialResources: ["industrialPatent"],
    baseStats: {
      economy: 70,
      industry: 58,
      defense: 50,
      population: 57,
      logistics: 76,
      marketScale: 72,
    },
  },
  hades: {
    id: "hades",
    name: "Hades",
    description: "방어와 중력 채굴이 강한 요새 행성.",
    defaultFactionId: "empire",
    profileId: "fortress",
    routeIds: ["atlas-hades", "hades-nyx"],
    citySlots: 2,
    resourceBias: {
      [CurrencyType.Materials]: 1.3,
      [CurrencyType.Gems]: 1.1,
    },
    specialResources: ["gravityOre"],
    baseStats: {
      economy: 45,
      industry: 75,
      defense: 92,
      population: 38,
      logistics: 48,
      marketScale: 35,
    },
  },
  nyx: {
    id: "nyx",
    name: "Nyx",
    description: "Hades 너머의 어두운 물질 채굴권. 위험하지만 전략 가치가 높다.",
    defaultFactionId: "empire",
    profileId: "dark-matter",
    routeIds: ["hades-nyx"],
    citySlots: 1,
    resourceBias: {
      [CurrencyType.Gems]: 1.2,
      [CurrencyType.Materials]: 1.15,
    },
    specialResources: ["darkMatter"],
    baseStats: {
      economy: 38,
      industry: 68,
      defense: 70,
      population: 24,
      logistics: 34,
      marketScale: 30,
    },
  },
};

// ─── 항로 정의 ────────────────────────────────────────────────────────────────

export const strategicRouteDefs: StrategicRouteDef[] = [
  { id: "atlas-hephaestus", fromPlanetId: "atlas",      toPlanetId: "hephaestus", baseDistance: 2 },
  { id: "atlas-athena",     fromPlanetId: "atlas",      toPlanetId: "athena",     baseDistance: 2 },
  { id: "atlas-eden",       fromPlanetId: "atlas",      toPlanetId: "eden",       baseDistance: 3 },
  { id: "atlas-hades",      fromPlanetId: "atlas",      toPlanetId: "hades",      baseDistance: 3 },
  { id: "hephaestus-selene",fromPlanetId: "hephaestus", toPlanetId: "selene",     baseDistance: 2 },
  { id: "sirius-orion",     fromPlanetId: "sirius",     toPlanetId: "orion",      baseDistance: 2 },
  { id: "sirius-vega",      fromPlanetId: "sirius",     toPlanetId: "vega",       baseDistance: 3 },
  { id: "vega-athena",      fromPlanetId: "vega",       toPlanetId: "athena",     baseDistance: 2 },
  { id: "eden-vega",        fromPlanetId: "eden",       toPlanetId: "vega",       baseDistance: 3 },
  { id: "hades-nyx",        fromPlanetId: "hades",      toPlanetId: "nyx",        baseDistance: 2 },
];

// ─── 초기 경쟁 도시 배치 (city seed) ─────────────────────────────────────────
// RivalCityManager가 초기화 시 이 목록을 읽어 도시 상태를 만든다.

export const initialRivalCitySeeds: RivalCitySeed[] = [
  {
    id: "rival-atlas-guild",
    cityDefId: "harbor_league",
    planetId: "atlas",
    factionId: "guild",
    name: "Atlas Harbor League",
    startingInfluence: 40,
  },
  {
    id: "rival-hephaestus-empire",
    cityDefId: "mountain_syndicate",
    planetId: "hephaestus",
    factionId: "empire",
    name: "Hephaestus Mountain Syndicate",
    startingInfluence: 35,
  },
  {
    id: "rival-eden-alliance",
    cityDefId: "forest_guild",
    planetId: "eden",
    factionId: "alliance",
    name: "Eden Forest Guild",
    startingInfluence: 38,
  },
];
