import { CurrencyType } from "@Glibs/inventory/wallet";
import { FactionId } from "@Glibs/gameobjects/turntypes";
import { StrategicPlanetCityKind, StrategicPlanetDef, StrategicRouteDef } from "./strategicgalaxytypes";
import { RivalCityDefId } from "@Glibs/gameobjects/rivalcity/rivalcitytypes";
import { MonsterId } from "@Glibs/actors/monsters/monstertypes";

// ─── 행성 Gameplay 정의 ───────────────────────────────────────────────────────

export const strategicPlanetDefs: Record<string, StrategicPlanetDef<RivalCityDefId>> = {
  atlas: {
    id: "atlas",
    name: "Atlas",
    description: "은하의 중앙 관문. 모든 주요 항로가 이곳을 통과한다.",
    defaultFactionId: "guild",
    profileId: "gateworld",
    routeIds: ["atlas-hephaestus", "atlas-athena", "atlas-hades"],
    citySlots: 3,
    cityPlacements: [
      {
        id: "rival-atlas-guild",
        kind: StrategicPlanetCityKind.Rival,
        cityDefId: RivalCityDefId.HarborLeague,
        factionId: FactionId.Guild,
        name: "Atlas Harbor League",
        startingInfluence: 40,
      },
    ],
    resourceBias: {
      [CurrencyType.Gold]: 1.3,
      [CurrencyType.Food]: 1.1,
    },
    specialResources: ["gateInfluence"],
    baseStats: {
      economy: 88,
      industry: 62,
      defense: 70,
      population: 74,
      logistics: 95,
      marketScale: 90,
    },
    combatWaves: [
      [MonsterId.Builder, MonsterId.Viking, MonsterId.Builder],
      [MonsterId.Viking, MonsterId.Golem, MonsterId.Viking],
      [MonsterId.Golem, MonsterId.Viking, MonsterId.Golem],
    ],
  },
  hephaestus: {
    id: "hephaestus",
    name: "Hephaestus",
    description: "대규모 조선소와 수리 독이 자리한 Guild 군수 성계.",
    defaultFactionId: "guild",
    profileId: "industrial",
    routeIds: ["atlas-hephaestus", "hephaestus-selene"],
    citySlots: 2,
    cityPlacements: [
      {
        id: "rival-hephaestus-empire",
        kind: StrategicPlanetCityKind.Rival,
        cityDefId: RivalCityDefId.MountainSyndicate,
        factionId: FactionId.Empire,
        name: "Hephaestus Mountain Syndicate",
        startingInfluence: 35,
      },
    ],
    resourceBias: {
      [CurrencyType.Materials]: 1.4,
      [CurrencyType.Gems]: 1.2,
    },
    specialResources: ["shipyardContract"],
    baseStats: {
      economy: 49,
      industry: 89,
      defense: 59,
      population: 41,
      logistics: 65,
      marketScale: 45,
    },
    combatWaves: [
      [MonsterId.Golem, MonsterId.Builder, MonsterId.Golem],
      [MonsterId.Builder, MonsterId.Golem, MonsterId.Builder],
      [MonsterId.Golem, MonsterId.BigGolem, MonsterId.Golem],
    ],
  },
  selene: {
    id: "selene",
    name: "Selene",
    description: "얼음 결정과 냉각 기술이 발달한 Hephaestus 외곽 위성권.",
    defaultFactionId: "guild",
    profileId: "ice-moon",
    routeIds: ["hephaestus-selene"],
    citySlots: 1,
    cityPlacements: [
      {
        id: "rival-selene-frontier",
        kind: StrategicPlanetCityKind.Rival,
        cityDefId: RivalCityDefId.FrontierCommune,
        factionId: FactionId.Guild,
        name: "Selene Frontier Commune",
        startingInfluence: 24,
      },
    ],
    resourceBias: {
      [CurrencyType.Water]: 1.25,
      [CurrencyType.Electric]: 1.1,
    },
    specialResources: ["iceCrystal"],
    baseStats: {
      economy: 40,
      industry: 55,
      defense: 48,
      population: 32,
      logistics: 52,
      marketScale: 38,
    },
    combatWaves: [
      [MonsterId.Skeleton, MonsterId.Snake, MonsterId.Skeleton],
      [MonsterId.Snake, MonsterId.Skeleton, MonsterId.Bilby],
      [MonsterId.Bilby, MonsterId.Skeleton, MonsterId.Snake],
    ],
  },
  eden: {
    id: "eden",
    name: "Eden",
    description: "풍요로운 생태계를 지닌 중립 식량 성계. 여러 세력이 탐내는 개척 대상이다.",
    defaultFactionId: FactionId.Neutral,
    profileId: "biosphere",
    routeIds: ["eden-vega"],
    citySlots: 3,
    cityPlacements: [
      {
        id: "player-city",
        kind: StrategicPlanetCityKind.Player,
        factionId: FactionId.Aetherion,
        name: "플레이어 도시",
      },
      {
        id: "rival-eden-neutral",
        kind: StrategicPlanetCityKind.Rival,
        cityDefId: RivalCityDefId.ForestGuild,
        factionId: FactionId.Neutral,
        name: "Eden Forest Guild",
        startingInfluence: 38,
      },
      {
        id: "native-eden-enclave",
        kind: StrategicPlanetCityKind.Native,
        cityDefId: RivalCityDefId.NativeEnclave,
        factionId: FactionId.Neutral,
        name: "에덴 원주민 구역",
        startingInfluence: 22,
      },
    ],
    resourceBias: {
      [CurrencyType.Food]: 1.5,
      [CurrencyType.Water]: 1.3,
    },
    specialResources: ["bioCrystal"],
    baseStats: {
      economy: 65,
      industry: 42,
      defense: 55,
      population: 88,
      logistics: 60,
      marketScale: 55,
    },
    combatWaves: [
      [MonsterId.Zombie, MonsterId.Birdmon, MonsterId.Zombie],
      [MonsterId.Birdmon, MonsterId.Snake, MonsterId.Birdmon],
      [MonsterId.Snake, MonsterId.Birdmon, MonsterId.Zombie],
    ],
  },
  sirius: {
    id: "sirius",
    name: "Sirius",
    description: "동부 외곽의 푸른 관문. 현재는 특정 진영이 깃발을 세우지 못한 전초 성계다.",
    defaultFactionId: FactionId.Neutral,
    profileId: "frontier",
    routeIds: ["sirius-orion", "sirius-vega"],
    citySlots: 2,
    cityPlacements: [
      {
        id: "rival-sirius-frontier",
        kind: StrategicPlanetCityKind.Rival,
        cityDefId: RivalCityDefId.FrontierCommune,
        factionId: FactionId.Neutral,
        name: "Sirius Frontier Commune",
        startingInfluence: 30,
      },
    ],
    resourceBias: {
      [CurrencyType.Electric]: 1.2,
    },
    specialResources: ["helium3"],
    baseStats: {
      economy: 62,
      industry: 58,
      defense: 54,
      population: 51,
      logistics: 55,
      marketScale: 40,
    },
    combatWaves: [
      [MonsterId.Viking, MonsterId.Zombie, MonsterId.Viking],
      [MonsterId.WereWolf, MonsterId.Viking, MonsterId.Zombie],
      [MonsterId.WereWolf, MonsterId.Viking, MonsterId.WereWolf],
    ],
  },
  orion: {
    id: "orion",
    name: "Orion",
    description: "Sirius 관문 너머의 헬륨 채굴 전초 성계.",
    defaultFactionId: "neutral",
    profileId: "gas-frontier",
    routeIds: ["sirius-orion"],
    citySlots: 1,
    cityPlacements: [
      {
        id: "rival-orion-frontier",
        kind: StrategicPlanetCityKind.Rival,
        cityDefId: RivalCityDefId.FrontierCommune,
        factionId: FactionId.Neutral,
        name: "Orion Frontier Commune",
        startingInfluence: 20,
      },
    ],
    resourceBias: {
      [CurrencyType.Electric]: 1.25,
      [CurrencyType.Materials]: 1.05,
    },
    specialResources: ["helium3"],
    baseStats: {
      economy: 46,
      industry: 54,
      defense: 42,
      population: 29,
      logistics: 47,
      marketScale: 34,
    },
    combatWaves: [
      [MonsterId.Bee, MonsterId.Birdmon, MonsterId.Bee],
      [MonsterId.Birdmon, MonsterId.Bilby, MonsterId.Bee],
      [MonsterId.Bee, MonsterId.Birdmon, MonsterId.Bilby],
    ],
  },
  vega: {
    id: "vega",
    name: "Vega",
    description: "동부 경제권의 물류가 통과하는 중립 상업 회랑 핵심 성계.",
    defaultFactionId: FactionId.Neutral,
    profileId: "trade",
    routeIds: ["sirius-vega", "vega-athena", "eden-vega"],
    citySlots: 3,
    cityPlacements: [
      {
        id: "rival-vega-harbor",
        kind: StrategicPlanetCityKind.Rival,
        cityDefId: RivalCityDefId.HarborLeague,
        factionId: FactionId.Neutral,
        name: "Vega Harbor League",
        startingInfluence: 36,
      },
    ],
    resourceBias: {
      [CurrencyType.Gold]: 1.2,
      [CurrencyType.Materials]: 1.1,
    },
    specialResources: ["rareEarth"],
    baseStats: {
      economy: 74,
      industry: 66,
      defense: 61,
      population: 65,
      logistics: 72,
      marketScale: 70,
    },
    combatWaves: [
      [MonsterId.Crab, MonsterId.Builder, MonsterId.Crab],
      [MonsterId.Viking, MonsterId.Crab, MonsterId.Builder],
      [MonsterId.Crab, MonsterId.Viking, MonsterId.Crab],
    ],
  },
  athena: {
    id: "athena",
    name: "Athena",
    description: "Atlas와 Vega를 잇는 연구·특허 교역 허브.",
    defaultFactionId: "guild",
    profileId: "research-hub",
    routeIds: ["atlas-athena", "vega-athena"],
    citySlots: 2,
    cityPlacements: [
      {
        id: "rival-athena-scholar",
        kind: StrategicPlanetCityKind.Rival,
        cityDefId: RivalCityDefId.ScholarEnclave,
        factionId: FactionId.Guild,
        name: "Athena Scholar Enclave",
        startingInfluence: 34,
      },
    ],
    resourceBias: {
      [CurrencyType.Gold]: 1.15,
      [CurrencyType.Electric]: 1.15,
    },
    specialResources: ["industrialPatent"],
    baseStats: {
      economy: 70,
      industry: 58,
      defense: 50,
      population: 57,
      logistics: 76,
      marketScale: 72,
    },
    combatWaves: [
      [MonsterId.ToadMage, MonsterId.Skeleton, MonsterId.ToadMage],
      [MonsterId.Skeleton, MonsterId.KittenMonk, MonsterId.ToadMage],
      [MonsterId.KittenMonk, MonsterId.ToadMage, MonsterId.KittenMonk],
    ],
  },
  hades: {
    id: "hades",
    name: "Hades",
    description: "방어와 중력 채굴이 강한 요새 행성.",
    defaultFactionId: "empire",
    profileId: "fortress",
    routeIds: ["atlas-hades", "hades-nyx"],
    citySlots: 2,
    cityPlacements: [
      {
        id: "rival-hades-syndicate",
        kind: StrategicPlanetCityKind.Rival,
        cityDefId: RivalCityDefId.MountainSyndicate,
        factionId: FactionId.Empire,
        name: "Hades Mountain Syndicate",
        startingInfluence: 33,
      },
    ],
    resourceBias: {
      [CurrencyType.Materials]: 1.3,
      [CurrencyType.Gems]: 1.1,
    },
    specialResources: ["gravityOre"],
    baseStats: {
      economy: 45,
      industry: 75,
      defense: 92,
      population: 38,
      logistics: 48,
      marketScale: 35,
    },
    combatWaves: [
      [MonsterId.Golem, MonsterId.Golem, MonsterId.Golem],
      [MonsterId.Golem, MonsterId.Minotaur, MonsterId.Golem],
      [MonsterId.Minotaur, MonsterId.BigGolem, MonsterId.Minotaur],
    ],
  },
  nyx: {
    id: "nyx",
    name: "Nyx",
    description: "Hades 너머의 어두운 물질 채굴권. 위험하지만 전략 가치가 높다.",
    defaultFactionId: "empire",
    profileId: "dark-matter",
    routeIds: ["hades-nyx"],
    citySlots: 1,
    cityPlacements: [
      {
        id: "rival-nyx-syndicate",
        kind: StrategicPlanetCityKind.Rival,
        cityDefId: RivalCityDefId.MountainSyndicate,
        factionId: FactionId.Empire,
        name: "Nyx Mountain Syndicate",
        startingInfluence: 22,
      },
    ],
    resourceBias: {
      [CurrencyType.Gems]: 1.2,
      [CurrencyType.Materials]: 1.15,
    },
    specialResources: ["darkMatter"],
    baseStats: {
      economy: 38,
      industry: 68,
      defense: 70,
      population: 24,
      logistics: 34,
      marketScale: 30,
    },
    combatWaves: [
      [MonsterId.Skeleton, MonsterId.WereWolf, MonsterId.Skeleton],
      [MonsterId.WereWolf, MonsterId.Skeleton, MonsterId.WereWolf],
      [MonsterId.WereWolf, MonsterId.BigGolem, MonsterId.WereWolf],
    ],
  },
};

// ─── 항로 정의 ────────────────────────────────────────────────────────────────

export const strategicRouteDefs: StrategicRouteDef[] = [
  { id: "atlas-hephaestus", fromPlanetId: "atlas",      toPlanetId: "hephaestus", baseDistance: 2 },
  { id: "atlas-athena",     fromPlanetId: "atlas",      toPlanetId: "athena",     baseDistance: 2 },
  { id: "atlas-hades",      fromPlanetId: "atlas",      toPlanetId: "hades",      baseDistance: 3 },
  { id: "hephaestus-selene",fromPlanetId: "hephaestus", toPlanetId: "selene",     baseDistance: 2 },
  { id: "sirius-orion",     fromPlanetId: "sirius",     toPlanetId: "orion",      baseDistance: 2 },
  { id: "sirius-vega",      fromPlanetId: "sirius",     toPlanetId: "vega",       baseDistance: 3 },
  { id: "vega-athena",      fromPlanetId: "vega",       toPlanetId: "athena",     baseDistance: 2 },
  { id: "eden-vega",        fromPlanetId: "eden",       toPlanetId: "vega",       baseDistance: 5 },
  { id: "hades-nyx",        fromPlanetId: "hades",      toPlanetId: "nyx",        baseDistance: 2 },
];
