import { GalaxyMapDef } from "./galaxytypes";

export const defaultGalaxyMap: GalaxyMapDef = {
    selectedPlanetId: "atlas",
    routes: [
        { id: "sirius-orion", fromPlanetId: "sirius", toPlanetId: "orion" },
        { id: "sirius-vega", fromPlanetId: "sirius", toPlanetId: "vega" },
        { id: "vega-athena", fromPlanetId: "vega", toPlanetId: "athena" },
        { id: "selene-hephaestus", fromPlanetId: "selene", toPlanetId: "hephaestus" },
        { id: "hephaestus-athena", fromPlanetId: "hephaestus", toPlanetId: "athena" },
        { id: "athena-atlas", fromPlanetId: "athena", toPlanetId: "atlas" },
        { id: "eos-artemis", fromPlanetId: "eos", toPlanetId: "artemis" },
        { id: "artemis-eden", fromPlanetId: "artemis", toPlanetId: "eden" },
        { id: "artemis-lyra", fromPlanetId: "artemis", toPlanetId: "lyra" },
        { id: "lyra-cygnus", fromPlanetId: "lyra", toPlanetId: "cygnus" },
        { id: "lyra-atlas", fromPlanetId: "lyra", toPlanetId: "atlas" },
        { id: "borealis-cygnus", fromPlanetId: "borealis", toPlanetId: "cygnus" },
        { id: "cygnus-titan", fromPlanetId: "cygnus", toPlanetId: "titan" },
        { id: "titan-zenith", fromPlanetId: "titan", toPlanetId: "zenith" },
        { id: "atlas-hades", fromPlanetId: "atlas", toPlanetId: "hades" },
        { id: "ares-apollo", fromPlanetId: "ares", toPlanetId: "apollo" },
        { id: "ares-hades", fromPlanetId: "ares", toPlanetId: "hades" },
        { id: "apollo-helios", fromPlanetId: "apollo", toPlanetId: "helios" },
        { id: "hades-nyx", fromPlanetId: "hades", toPlanetId: "nyx" },
        { id: "nyx-draco", fromPlanetId: "nyx", toPlanetId: "draco" },
        { id: "draco-nova", fromPlanetId: "draco", toPlanetId: "nova" },
    ],
    planets: [
        {
            id: "sirius",
            name: "Sirius",
            factionId: "alliance",
            radius: 1.02,
            assetKey: "amberBands",
            stats: { economy: 62, industry: 58, defense: 54, stationedFleet: 24, population: 51, resource: "헬륨-3" },
            description: "동부 외곽의 푸른 관문. Alliance 정찰대가 가장 먼저 배치되는 전초 성계다.",
        },
        {
            id: "orion",
            name: "Orion",
            factionId: "neutral",
            radius: 1.45,
            assetKey: "azureIce",
            stats: { economy: 53, industry: 42, defense: 46, stationedFleet: 16, population: 37, resource: "빙정 광물" },
            description: "중립 감시권의 대표 성계. 외곽 관측과 중재 역할을 수행한다.",
        },
        {
            id: "vega",
            name: "Vega",
            factionId: "alliance",
            radius: 1.27,
            assetKey: "roseSpots",
            stats: { economy: 74, industry: 66, defense: 61, stationedFleet: 33, population: 65, resource: "희토류" },
            description: "Alliance의 상업 회랑 핵심. 동부 경제권의 물류가 이곳을 통과한다.",
        },
        {
            id: "selene",
            name: "Selene",
            factionId: "neutral",
            radius: 1.24,
            assetKey: "azureIce",
            stats: { economy: 43, industry: 37, defense: 44, stationedFleet: 12, population: 29, resource: "저온 수자원" },
            description: "후방 보급의 조용한 중계점. 외형은 고요하지만 항로상 가치는 높다.",
        },
        {
            id: "hephaestus",
            name: "Hephaestus",
            factionId: "guild",
            radius: 1.12,
            assetKey: "amberBands",
            stats: { economy: 49, industry: 89, defense: 59, stationedFleet: 22, population: 41, resource: "조선 공업" },
            description: "대규모 조선소와 수리 독이 자리한 Guild 군수 성계다.",
        },
        {
            id: "athena",
            name: "Athena",
            factionId: "alliance",
            radius: 1.33,
            assetKey: "roseSpots",
            stats: { economy: 71, industry: 60, defense: 73, stationedFleet: 31, population: 58, resource: "정보 네트워크" },
            description: "Alliance 전략사령부가 위치한 지성 성계. 전선 재배치 명령이 집중된다.",
        },
        {
            id: "eos",
            name: "Eos",
            factionId: "alliance",
            radius: 1.29,
            assetKey: "roseSpots",
            stats: { economy: 64, industry: 55, defense: 63, stationedFleet: 27, population: 49, resource: "플라즈마 섬유" },
            description: "Alliance 남동 전선의 새벽 거점. 반격 작전의 출발점으로 쓰인다.",
        },
        {
            id: "artemis",
            name: "Artemis",
            factionId: "alliance",
            radius: 1.56,
            assetKey: "azureIce",
            stats: { economy: 68, industry: 57, defense: 71, stationedFleet: 36, population: 55, resource: "희귀 생체광물" },
            description: "Alliance의 기동 방어 거점. 남부 회랑의 핵심 연결점이다.",
        },
        {
            id: "eden",
            name: "Eden",
            factionId: "alliance",
            radius: 1.47,
            assetKey: "azureIce",
            stats: { economy: 72, industry: 52, defense: 66, stationedFleet: 30, population: 61, resource: "생명수정" },
            description: "Alliance 후방 회복권. 정비와 보급, 회복 기능이 강한 안정 성계다.",
        },
        {
            id: "lyra",
            name: "Lyra",
            factionId: "guild",
            radius: 1.48,
            assetKey: "cobaltSwirl",
            stats: { economy: 83, industry: 54, defense: 58, stationedFleet: 21, population: 62, resource: "문화 데이터" },
            description: "Guild 문화·외교의 중심축. 중앙 회랑의 완충 성계다.",
        },
        {
            id: "borealis",
            name: "Borealis",
            factionId: "guild",
            radius: 1.52,
            assetKey: "cobaltSwirl",
            ring: { textureKey: "aurora", tiltX: 0.60, tiltY: 0.42 },
            stats: { economy: 86, industry: 59, defense: 60, stationedFleet: 23, population: 68, resource: "오로라 결정" },
            description: "Guild 북광 무역권의 상징 성계. 고급 자원 거래가 집중된다.",
        },
        {
            id: "cygnus",
            name: "Cygnus",
            factionId: "neutral",
            radius: 1.36,
            assetKey: "amberBands",
            stats: { economy: 55, industry: 49, defense: 52, stationedFleet: 18, population: 44, resource: "정제 가스" },
            description: "중립 무역 정박지. 전선 사이에서 숨통을 틔워주는 회랑의 쉼터다.",
        },
        {
            id: "titan",
            name: "Titan",
            factionId: "neutral",
            radius: 1.72,
            assetKey: "amberBands",
            ring: { textureKey: "prism", tiltX: 0.67, tiltY: 0.24 },
            stats: { economy: 60, industry: 69, defense: 70, stationedFleet: 29, population: 57, resource: "거대 위성 자원" },
            description: "대형 정거장과 위성 공업권이 연결된 중립 대성계다.",
        },
        {
            id: "zenith",
            name: "Zenith",
            factionId: "guild",
            radius: 1.85,
            assetKey: "cobaltSwirl",
            ring: { textureKey: "aurora", tiltX: 0.52, tiltY: 0.71 },
            stats: { economy: 94, industry: 70, defense: 58, stationedFleet: 24, population: 84, resource: "초광속 데이터" },
            description: "서단 무역권의 종착점. 거대한 교역망의 끝이자 새로운 항로의 시작점이다.",
        },
        {
            id: "atlas",
            name: "Atlas",
            factionId: "neutral",
            radius: 1.58,
            assetKey: "azureIce",
            stats: { economy: 79, industry: 77, defense: 69, stationedFleet: 28, population: 69, resource: "중앙 관문" },
            description: "은하 중앙 회랑의 균형추. 여러 세력이 접근하지만 누구도 쉽게 독점하지 못하는 핵심 허브다.",
        },
        {
            id: "ares",
            name: "Ares",
            factionId: "empire",
            radius: 1.54,
            assetKey: "basaltCracks",
            ring: { textureKey: "prism", tiltX: 0.76, tiltY: 0.58 },
            stats: { economy: 58, industry: 81, defense: 88, stationedFleet: 42, population: 48, resource: "중금속 광맥" },
            description: "Empire 전초 군항. 전선 돌파용 중함대가 상시 대기하는 군사 거점이다.",
        },
        {
            id: "apollo",
            name: "Apollo",
            factionId: "guild",
            radius: 1.81,
            assetKey: "cobaltSwirl",
            stats: { economy: 88, industry: 63, defense: 57, stationedFleet: 26, population: 74, resource: "태양풍 에너지" },
            description: "Guild 상업 연합의 밝은 교역 성계. 고부가 교역선이 밀집한다.",
        },
        {
            id: "helios",
            name: "Helios",
            factionId: "guild",
            radius: 1.88,
            assetKey: "cobaltSwirl",
            stats: { economy: 91, industry: 72, defense: 55, stationedFleet: 25, population: 81, resource: "광자 연료" },
            description: "Guild 외곽 금융권. 민간 수송과 상업 함대가 밀집한 부유한 성계다.",
        },
        {
            id: "hades",
            name: "Hades",
            factionId: "empire",
            radius: 1.66,
            assetKey: "basaltCracks",
            ring: { textureKey: "aurora", tiltX: 0.54, tiltY: 0.88 },
            stats: { economy: 66, industry: 84, defense: 92, stationedFleet: 48, population: 52, resource: "중력 채굴" },
            description: "Empire 내해의 핵심 요새. 봉쇄와 방어 작전에 최적화된 성계다.",
        },
        {
            id: "nyx",
            name: "Nyx",
            factionId: "empire",
            radius: 1.43,
            assetKey: "roseSpots",
            ring: { textureKey: "prism", tiltX: 0.85, tiltY: 0.34 },
            stats: { economy: 57, industry: 64, defense: 76, stationedFleet: 34, population: 46, resource: "암흑물질" },
            description: "Empire의 음영 항로 입구. 야간 기동과 매복이 자주 발생한다.",
        },
        {
            id: "draco",
            name: "Draco",
            factionId: "empire",
            radius: 1.61,
            assetKey: "basaltCracks",
            stats: { economy: 59, industry: 78, defense: 82, stationedFleet: 37, population: 47, resource: "초경질 합금" },
            description: "Empire 남부 회랑을 지키는 장갑 성계. 강한 저지력이 특징이다.",
        },
        {
            id: "nova",
            name: "Nova",
            factionId: "empire",
            radius: 1.40,
            assetKey: "roseSpots",
            stats: { economy: 63, industry: 67, defense: 74, stationedFleet: 32, population: 53, resource: "폭발성 광석" },
            description: "Empire의 돌격 준비 거점. 빠른 공세 전환에 적합한 위치를 가진다.",
        }
    ]
};
